
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/terraform-aws-modules/terraform-aws-eks.git?ref=v21.9.0"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Controls if resources should be created (affects nearly all resources)
  # Type: bool
  # create = true

  # Description: Name of the IAM role
  # Type: string
  # name = "EKSHybridNode"

  # Description: Determines whether the name of the IAM role (`name`) is used as a prefix
  # Type: bool
  # use_name_prefix = true

  # Description: Path of the IAM role
  # Type: string
  # path = "/"

  # Description: IAM role description
  # Type: string
  # description = "EKS Hybrid Node IAM role"

  # Description: Maximum API session duration in seconds between 3600 and 43200
  # Type: number
  # max_session_duration = null

  # Description: Permissions boundary ARN to use for the IAM role
  # Type: string
  # permissions_boundary_arn = null

  # Description: A map of additional tags to add the the IAM role
  # Type: map
  # tags = {}

  # Description: Enables IAM Roles Anywhere based IAM permissions on the node
  # Type: bool
  # enable_ira = false

  # Description: List of IAM Roles Anywhere trust anchor ARNs. Required if `enable_ira` is set to `true`
  # Type: list
  # trust_anchor_arns = []

  # Description: Name of the IAM policy
  # Type: string
  # policy_name = "EKSHybridNode"

  # Description: Determines whether the name of the IAM policy (`policy_name`) is used as a prefix
  # Type: bool
  # policy_use_name_prefix = true

  # Description: Path of the IAM policy
  # Type: string
  # policy_path = "/"

  # Description: IAM policy description
  # Type: string
  # policy_description = "EKS Hybrid Node IAM role policy"

  # Description: A list of IAM policy [statements](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#statement) - used for adding specific IAM permissions as needed
  # Type: list
  # policy_statements = null

  # Description: Policies to attach to the IAM role in `{'static_name' = 'policy_arn'}` format
  # Type: map
  # policies = {}

  # Description: List of EKS cluster ARNs to allow the node to describe
  # Type: list
  # cluster_arns = ["*"]

  # Description: Enables EKS Pod Identity based IAM permissions on the node
  # Type: bool
  # enable_pod_identity = true

  # Description: Name of the Roles Anywhere profile
  # Type: string
  # ira_profile_name = null

  # Description: The number of seconds the vended session credentials are valid for. Defaults to `3600`
  # Type: number
  # ira_profile_duration_seconds = null

  # Description: A list of managed policy ARNs that apply to the vended session credentials
  # Type: list
  # ira_profile_managed_policy_arns = []

  # Description: Specifies whether instance properties are required in [CreateSession](https://docs.aws.amazon.com/rolesanywhere/latest/APIReference/API_CreateSession.html) requests with this profile
  # Type: bool
  # ira_profile_require_instance_properties = null

  # Description: A session policy that applies to the trust boundary of the vended session credentials
  # Type: string
  # ira_profile_session_policy = null

  # Description: Name of the Roles Anywhere trust anchor
  # Type: string
  # ira_trust_anchor_name = null

  # Description: Notification settings for the trust anchor
  # Type: list
  # ira_trust_anchor_notification_settings = null

  # Description: The ARN of the ACM PCA that issued the trust anchor certificate
  # Type: string
  # ira_trust_anchor_acm_pca_arn = null

  # Description: The X.509 certificate data of the trust anchor
  # Type: string
  # ira_trust_anchor_x509_certificate_data = null

  # Description: The source type of the trust anchor
  # Type: string
  # ira_trust_anchor_source_type = null

  # Description: Name of the IAM role
  # Type: string
  # intermediate_role_name = null

  # Description: Determines whether the name of the IAM role (`intermediate_role_name`) is used as a prefix
  # Type: bool
  # intermediate_role_use_name_prefix = true

  # Description: Path of the IAM role
  # Type: string
  # intermediate_role_path = "/"

  # Description: IAM role description
  # Type: string
  # intermediate_role_description = "EKS Hybrid Node IAM Roles Anywhere intermediate IAM role"

  # Description: Name of the IAM policy
  # Type: string
  # intermediate_policy_name = null

  # Description: Determines whether the name of the IAM policy (`intermediate_policy_name`) is used as a prefix
  # Type: bool
  # intermediate_policy_use_name_prefix = true

  # Description: A list of IAM policy [statements](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#statement) - used for adding specific IAM permissions as needed
  # Type: list
  # intermediate_policy_statements = null

  # Description: Policies to attach to the IAM role in `{'static_name' = 'policy_arn'}` format
  # Type: map
  # intermediate_role_policies = {}

  # Description: Controls if resources should be created (affects nearly all resources)
  # Type: bool
  # create = true

  # Description: The separator to use between the prefix and the generated timestamp for resource names
  # Type: string
  # prefix_separator = "-"

  # Description: Region where the resource(s) will be managed. Defaults to the Region set in the provider configuration
  # Type: string
  # region = null

  # Description: A map of tags to add to all resources
  # Type: map
  # tags = {}

  # Description: Name of the EKS cluster
  # Type: string
  # name = ""

  # Description: Kubernetes `<major>.<minor>` version to use for the EKS cluster (i.e.: `1.33`)
  # Type: string
  # kubernetes_version = null

  # Description: A list of the desired control plane logs to enable. For more information, see Amazon EKS Control Plane Logging documentation (https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html)
  # Type: list
  # enabled_log_types = ["audit","api","authenticator"]

  # Description: Whether to enable deletion protection for the cluster. When enabled, the cluster cannot be deleted unless deletion protection is first disabled
  # Type: bool
  # deletion_protection = null

  # Description: Force version update by overriding upgrade-blocking readiness checks when updating a cluster
  # Type: bool
  # force_update_version = null

  # Description: The authentication mode for the cluster. Valid values are `CONFIG_MAP`, `API` or `API_AND_CONFIG_MAP`
  # Type: string
  # authentication_mode = "API_AND_CONFIG_MAP"

  # Description: Configuration block for the cluster compute configuration
  # Type: object
  # compute_config = null

  # Description: Configuration block for the cluster upgrade policy
  # Type: object
  # upgrade_policy = null

  # Description: Configuration block for the cluster remote network configuration
  # Type: object
  # remote_network_config = null

  # Description: Configuration block for the cluster zonal shift
  # Type: object
  # zonal_shift_config = null

  # Description: List of additional, externally created security group IDs to attach to the cluster control plane
  # Type: list
  # additional_security_group_ids = []

  # Description: A list of subnet IDs where the EKS cluster control plane (ENIs) will be provisioned. Used for expanding the pool of subnets used by nodes/node groups without replacing the EKS control plane
  # Type: list
  # control_plane_subnet_ids = []

  # Description: A list of subnet IDs where the nodes/node groups will be provisioned. If `control_plane_subnet_ids` is not provided, the EKS cluster control plane (ENIs) will be provisioned in these subnets
  # Type: list
  # subnet_ids = []

  # Description: Indicates whether or not the Amazon EKS private API server endpoint is enabled
  # Type: bool
  # endpoint_private_access = true

  # Description: Indicates whether or not the Amazon EKS public API server endpoint is enabled
  # Type: bool
  # endpoint_public_access = false

  # Description: List of CIDR blocks which can access the Amazon EKS public API server endpoint
  # Type: list
  # endpoint_public_access_cidrs = ["0.0.0.0/0"]

  # Description: The IP family used to assign Kubernetes pod and service addresses. Valid values are `ipv4` (default) and `ipv6`. You can only specify an IP family when you create a cluster, changing this value will force a new cluster to be created
  # Type: string
  # ip_family = "ipv4"

  # Description: The CIDR block to assign Kubernetes service IP addresses from. If you don't specify a block, Kubernetes assigns addresses from either the 10.100.0.0/16 or 172.20.0.0/16 CIDR blocks
  # Type: string
  # service_ipv4_cidr = null

  # Description: The CIDR block to assign Kubernetes pod and service IP addresses from if `ipv6` was specified when the cluster was created. Kubernetes assigns service addresses from the unique local address range (fc00::/7) because you can't specify a custom IPv6 CIDR block when you create the cluster
  # Type: string
  # service_ipv6_cidr = null

  # Description: Configuration for the AWS Outpost to provision the cluster on
  # Type: object
  # outpost_config = null

  # Description: Configuration block with encryption configuration for the cluster
  # Type: object
  # encryption_config = {}

  # Description: Indicates whether or not to attach an additional policy for the cluster IAM role to utilize the encryption key provided
  # Type: bool
  # attach_encryption_policy = true

  # Description: A map of additional tags to add to the cluster
  # Type: map
  # cluster_tags = {}

  # Description: Indicates whether or not to tag the cluster's primary security group. This security group is created by the EKS service, not the module, and therefore tagging is handled after cluster creation
  # Type: bool
  # create_primary_security_group_tags = true

  # Description: Create, update, and delete timeout configurations for the cluster
  # Type: object
  # timeouts = null

  # Description: Map of access entries to add to the cluster
  # Type: map
  # access_entries = {}

  # Description: Indicates whether or not to add the cluster creator (the identity used by Terraform) as an administrator via access entry
  # Type: bool
  # enable_cluster_creator_admin_permissions = false

  # Description: Controls if a KMS key for cluster encryption should be created
  # Type: bool
  # create_kms_key = true

  # Description: The description of the key as viewed in AWS console
  # Type: string
  # kms_key_description = null

  # Description: The waiting period, specified in number of days. After the waiting period ends, AWS KMS deletes the KMS key. If you specify a value, it must be between `7` and `30`, inclusive. If you do not specify a value, it defaults to `30`
  # Type: number
  # kms_key_deletion_window_in_days = null

  # Description: Specifies whether key rotation is enabled
  # Type: bool
  # enable_kms_key_rotation = true

  # Description: Custom period of time between each key rotation date. If you specify a value, it must be between `90` and `2560`, inclusive. If you do not specify a value, it defaults to `365`
  # Type: number
  # kms_key_rotation_period_in_days = null

  # Description: Specifies whether to enable the default key policy
  # Type: bool
  # kms_key_enable_default_policy = true

  # Description: A list of IAM ARNs for those who will have full key permissions (`kms:*`)
  # Type: list
  # kms_key_owners = []

  # Description: A list of IAM ARNs for [key administrators](https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html#key-policy-default-allow-administrators). If no value is provided, the current caller identity is used to ensure at least one key admin is available
  # Type: list
  # kms_key_administrators = []

  # Description: A list of IAM ARNs for [key users](https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html#key-policy-default-allow-users)
  # Type: list
  # kms_key_users = []

  # Description: A list of IAM ARNs for [key service users](https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html#key-policy-service-integration)
  # Type: list
  # kms_key_service_users = []

  # Description: List of IAM policy documents that are merged together into the exported document. Statements must have unique `sid`s
  # Type: list
  # kms_key_source_policy_documents = []

  # Description: List of IAM policy documents that are merged together into the exported document. In merging, statements with non-blank `sid`s will override statements with the same `sid`
  # Type: list
  # kms_key_override_policy_documents = []

  # Description: A list of aliases to create. Note - due to the use of `toset()`, values must be static strings and not computed values
  # Type: list
  # kms_key_aliases = []

  # Description: Determines whether a log group is created by this module for the cluster logs. If not, AWS will automatically create one if logging is enabled
  # Type: bool
  # create_cloudwatch_log_group = true

  # Description: Number of days to retain log events. Default retention - 90 days
  # Type: number
  # cloudwatch_log_group_retention_in_days = 90

  # Description: If a KMS Key ARN is set, this key will be used to encrypt the corresponding log group. Please be sure that the KMS Key has an appropriate key policy (https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/encrypt-log-data-kms.html)
  # Type: string
  # cloudwatch_log_group_kms_key_id = null

  # Description: Specified the log class of the log group. Possible values are: `STANDARD` or `INFREQUENT_ACCESS`
  # Type: string
  # cloudwatch_log_group_class = null

  # Description: A map of additional tags to add to the cloudwatch log group created
  # Type: map
  # cloudwatch_log_group_tags = {}

  # Description: Determines if a security group is created for the cluster. Note: the EKS service creates a primary security group for the cluster by default
  # Type: bool
  # create_security_group = true

  # Description: Existing security group ID to be attached to the cluster
  # Type: string
  # security_group_id = ""

  # Description: ID of the VPC where the cluster security group will be provisioned
  # Type: string
  # vpc_id = null

  # Description: Name to use on cluster security group created
  # Type: string
  # security_group_name = null

  # Description: Determines whether cluster security group name (`cluster_security_group_name`) is used as a prefix
  # Type: bool
  # security_group_use_name_prefix = true

  # Description: Description of the cluster security group created
  # Type: string
  # security_group_description = "EKS cluster security group"

  # Description: List of additional security group rules to add to the cluster security group created. Set `source_node_security_group = true` inside rules to set the `node_security_group` as source
  # Type: map
  # security_group_additional_rules = {}

  # Description: A map of additional tags to add to the cluster security group created
  # Type: map
  # security_group_tags = {}

  # Description: Determines whether to create an [`AmazonEKS_CNI_IPv6_Policy`](https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html#cni-iam-role-create-ipv6-policy)
  # Type: bool
  # create_cni_ipv6_iam_policy = false

  # Description: Determines whether to create a security group for the node groups or use the existing `node_security_group_id`
  # Type: bool
  # create_node_security_group = true

  # Description: ID of an existing security group to attach to the node groups created
  # Type: string
  # node_security_group_id = ""

  # Description: Name to use on node security group created
  # Type: string
  # node_security_group_name = null

  # Description: Determines whether node security group name (`node_security_group_name`) is used as a prefix
  # Type: bool
  # node_security_group_use_name_prefix = true

  # Description: Description of the node security group created
  # Type: string
  # node_security_group_description = "EKS node shared security group"

  # Description: List of additional security group rules to add to the node security group created. Set `source_cluster_security_group = true` inside rules to set the `cluster_security_group` as source
  # Type: map
  # node_security_group_additional_rules = {}

  # Description: Determines whether to enable recommended security group rules for the node security group created. This includes node-to-node TCP ingress on ephemeral ports and allows all egress traffic
  # Type: bool
  # node_security_group_enable_recommended_rules = true

  # Description: A map of additional tags to add to the node security group created
  # Type: map
  # node_security_group_tags = {}

  # Description: Determines whether to create an OpenID Connect Provider for EKS to enable IRSA
  # Type: bool
  # enable_irsa = true

  # Description: List of OpenID Connect audience client IDs to add to the IRSA provider
  # Type: list
  # openid_connect_audiences = []

  # Description: Determines whether to include the root CA thumbprint in the OpenID Connect (OIDC) identity provider's server certificate(s)
  # Type: bool
  # include_oidc_root_ca_thumbprint = true

  # Description: Additional list of server certificate thumbprints for the OpenID Connect (OIDC) identity provider's server certificate(s)
  # Type: list
  # custom_oidc_thumbprints = []

  # Description: Determines whether an IAM role is created for the cluster
  # Type: bool
  # create_iam_role = true

  # Description: Existing IAM role ARN for the cluster. Required if `create_iam_role` is set to `false`
  # Type: string
  # iam_role_arn = null

  # Description: Name to use on IAM role created
  # Type: string
  # iam_role_name = null

  # Description: Determines whether the IAM role name (`iam_role_name`) is used as a prefix
  # Type: bool
  # iam_role_use_name_prefix = true

  # Description: The IAM role path
  # Type: string
  # iam_role_path = null

  # Description: Description of the role
  # Type: string
  # iam_role_description = null

  # Description: ARN of the policy that is used to set the permissions boundary for the IAM role
  # Type: string
  # iam_role_permissions_boundary = null

  # Description: Additional policies to be added to the IAM role
  # Type: map
  # iam_role_additional_policies = {}

  # Description: A map of additional tags to add to the IAM role created
  # Type: map
  # iam_role_tags = {}

  # Description: Determines whether cluster encryption policy name (`cluster_encryption_policy_name`) is used as a prefix
  # Type: bool
  # encryption_policy_use_name_prefix = true

  # Description: Name to use on cluster encryption policy created
  # Type: string
  # encryption_policy_name = null

  # Description: Description of the cluster encryption policy created
  # Type: string
  # encryption_policy_description = "Cluster encryption policy to allow cluster role to utilize CMK provided"

  # Description: Cluster encryption policy path
  # Type: string
  # encryption_policy_path = null

  # Description: A map of additional tags to add to the cluster encryption policy created
  # Type: map
  # encryption_policy_tags = {}

  # Description: Duration to wait after the EKS cluster has become active before creating the dataplane components (EKS managed node group(s), self-managed node group(s), Fargate profile(s))
  # Type: string
  # dataplane_wait_duration = "30s"

  # Description: Determines whether to enable permissions for custom tags resources created by EKS Auto Mode
  # Type: bool
  # enable_auto_mode_custom_tags = true

  # Description: Determines whether to create/attach IAM resources for EKS Auto Mode. Useful for when using only custom node pools and not built-in EKS Auto Mode node pools
  # Type: bool
  # create_auto_mode_iam_resources = false

  # Description: Map of cluster addon configurations to enable for the cluster. Addon name can be the map keys or set with `name`
  # Type: map
  # addons = null

  # Description: Create, update, and delete timeout configurations for the cluster addons
  # Type: object
  # addons_timeouts = {}

  # Description: Map of cluster identity provider configurations to enable for the cluster. Note - this is different/separate from IRSA
  # Type: map
  # identity_providers = null

  # Description: Determines whether an EKS Auto node IAM role is created
  # Type: bool
  # create_node_iam_role = true

  # Description: Name to use on the EKS Auto node IAM role created
  # Type: string
  # node_iam_role_name = null

  # Description: Determines whether the EKS Auto node IAM role name (`node_iam_role_name`) is used as a prefix
  # Type: bool
  # node_iam_role_use_name_prefix = true

  # Description: The EKS Auto node IAM role path
  # Type: string
  # node_iam_role_path = null

  # Description: Description of the EKS Auto node IAM role
  # Type: string
  # node_iam_role_description = null

  # Description: ARN of the policy that is used to set the permissions boundary for the EKS Auto node IAM role
  # Type: string
  # node_iam_role_permissions_boundary = null

  # Description: Additional policies to be added to the EKS Auto node IAM role
  # Type: map
  # node_iam_role_additional_policies = {}

  # Description: A map of additional tags to add to the EKS Auto node IAM role created
  # Type: map
  # node_iam_role_tags = {}

  # Description: Map of Fargate Profile definitions to create
  # Type: map
  # fargate_profiles = null

  # Description: Map of self-managed node group definitions to create
  # Type: map
  # self_managed_node_groups = null

  # Description: Map of EKS managed node group definitions to create
  # Type: map
  # eks_managed_node_groups = null

  # Description: Do you agree that Putin doesn't respect Ukrainian sovereignty and territorial integrity? More info: https://en.wikipedia.org/wiki/Putin_khuylo!
  # Type: bool
  # putin_khuylo = true

  # Description: Determines whether to create user-data or not
  # Type: bool
  # create = true

  # Description: Type of Amazon Machine Image (AMI) associated with the EKS Node Group. See the [AWS documentation](https://docs.aws.amazon.com/eks/latest/APIReference/API_Nodegroup.html#AmazonEKS-Type-Nodegroup-amiType) for valid values
  # Type: string
  # ami_type = "AL2023_x86_64_STANDARD"

  # Description: Determines whether the bootstrap configurations are populated within the user data template
  # Type: bool
  # enable_bootstrap_user_data = false

  # Description: Determines whether the user data is used on nodes in an EKS managed node group. Used to determine if user data will be appended or not
  # Type: bool
  # is_eks_managed_node_group = true

  # Description: Name of the EKS cluster
  # Type: string
  # cluster_name = ""

  # Description: Endpoint of associated EKS cluster
  # Type: string
  # cluster_endpoint = ""

  # Description: Base64 encoded CA of associated EKS cluster
  # Type: string
  # cluster_auth_base64 = ""

  # Description: The CIDR block (IPv4 or IPv6) used by the cluster to assign Kubernetes service IP addresses. This is derived from the cluster itself
  # Type: string
  # cluster_service_cidr = ""

  # Description: The IP family used to assign Kubernetes pod and service addresses. Valid values are `ipv4` (default) and `ipv6`
  # Type: string
  # cluster_ip_family = "ipv4"

  # Description: Additional DNS IP addresses to use for the cluster. Only used when `ami_type` = `BOTTLEROCKET_*`
  # Type: list
  # additional_cluster_dns_ips = []

  # Description: User data that is injected into the user data script ahead of the EKS bootstrap script. Not used when `ami_type` = `BOTTLEROCKET_*`
  # Type: string
  # pre_bootstrap_user_data = ""

  # Description: User data that is appended to the user data script after of the EKS bootstrap script. Not used when `ami_type` = `BOTTLEROCKET_*`
  # Type: string
  # post_bootstrap_user_data = ""

  # Description: Additional arguments passed to the bootstrap script. When `ami_type` = `BOTTLEROCKET_*`; these are additional [settings](https://github.com/bottlerocket-os/bottlerocket#settings) that are provided to the Bottlerocket user data
  # Type: string
  # bootstrap_extra_args = ""

  # Description: Path to a local, custom user data template file to use when rendering user data
  # Type: string
  # user_data_template_path = ""

  # Description: Array of cloud-init document parts that are created before the nodeadm document part
  # Type: list
  # cloudinit_pre_nodeadm = []

  # Description: Array of cloud-init document parts that are created after the nodeadm document part
  # Type: list
  # cloudinit_post_nodeadm = []

  # Description: Determines whether to create self managed node group or not
  # Type: bool
  # create = true

  # Description: A map of tags to add to all resources
  # Type: map
  # tags = {}

  # Description: Region where the resource(s) will be managed. Defaults to the Region set in the provider configuration
  # Type: string
  # region = null

  # Description: The AWS partition - pass through value to reduce number of GET requests from data sources
  # Type: string
  # partition = ""

  # Description: The AWS account ID - pass through value to reduce number of GET requests from data sources
  # Type: string
  # account_id = ""

  # Description: Name of associated EKS cluster
  # Type: string
  # cluster_name = ""

  # Description: Endpoint of associated EKS cluster
  # Type: string
  # cluster_endpoint = null

  # Description: Base64 encoded CA of associated EKS cluster
  # Type: string
  # cluster_auth_base64 = null

  # Description: The CIDR block (IPv4 or IPv6) used by the cluster to assign Kubernetes service IP addresses. This is derived from the cluster itself
  # Type: string
  # cluster_service_cidr = null

  # Description: The IP family used to assign Kubernetes pod and service addresses. Valid values are `ipv4` (default) and `ipv6`
  # Type: string
  # cluster_ip_family = null

  # Description: Additional DNS IP addresses to use for the cluster. Only used when `ami_type` = `BOTTLEROCKET_*`
  # Type: list
  # additional_cluster_dns_ips = null

  # Description: User data that is injected into the user data script ahead of the EKS bootstrap script. Not used when `ami_type` = `BOTTLEROCKET_*`
  # Type: string
  # pre_bootstrap_user_data = null

  # Description: User data that is appended to the user data script after of the EKS bootstrap script. Not used when `ami_type` = `BOTTLEROCKET_*`
  # Type: string
  # post_bootstrap_user_data = null

  # Description: Additional arguments passed to the bootstrap script. When `ami_type` = `BOTTLEROCKET_*`; these are additional [settings](https://github.com/bottlerocket-os/bottlerocket#settings) that are provided to the Bottlerocket user data
  # Type: string
  # bootstrap_extra_args = null

  # Description: Path to a local, custom user data template file to use when rendering user data
  # Type: string
  # user_data_template_path = null

  # Description: Array of cloud-init document parts that are created before the nodeadm document part
  # Type: list
  # cloudinit_pre_nodeadm = null

  # Description: Array of cloud-init document parts that are created after the nodeadm document part
  # Type: list
  # cloudinit_post_nodeadm = null

  # Description: Determines whether to create launch template or not
  # Type: bool
  # create_launch_template = true

  # Description: The ID of an existing launch template to use. Required when `create_launch_template` = `false`
  # Type: string
  # launch_template_id = ""

  # Description: Name of launch template to be created
  # Type: string
  # launch_template_name = null

  # Description: Determines whether to use `launch_template_name` as is or create a unique name beginning with the `launch_template_name` as the prefix
  # Type: bool
  # launch_template_use_name_prefix = true

  # Description: Description of the launch template
  # Type: string
  # launch_template_description = null

  # Description: Default Version of the launch template
  # Type: string
  # launch_template_default_version = null

  # Description: Whether to update Default Version each update. Conflicts with `launch_template_default_version`
  # Type: bool
  # update_launch_template_default_version = true

  # Description: If true, enables EC2 instance termination protection
  # Type: bool
  # disable_api_termination = null

  # Description: Shutdown behavior for the instance. Can be `stop` or `terminate`. (Default: `stop`)
  # Type: string
  # instance_initiated_shutdown_behavior = null

  # Description: The kernel ID
  # Type: string
  # kernel_id = null

  # Description: The ID of the ram disk
  # Type: string
  # ram_disk_id = null

  # Description: Specify volumes to attach to the instance besides the volumes specified by the AMI
  # Type: map
  # block_device_mappings = null

  # Description: Targeting for EC2 capacity reservations
  # Type: object
  # capacity_reservation_specification = null

  # Description: The CPU options for the instance
  # Type: object
  # cpu_options = null

  # Description: Customize the credit specification of the instance
  # Type: object
  # credit_specification = null

  # Description: Enable Nitro Enclaves on launched instances
  # Type: object
  # enclave_options = null

  # Description: The market (purchasing) option for the instance
  # Type: object
  # instance_market_options = null

  # Description: The maintenance options for the instance
  # Type: object
  # maintenance_options = null

  # Description: A list of license specifications to associate with
  # Type: list
  # license_specifications = null

  # Description: Customize network interfaces to be attached at instance boot time
  # Type: list
  # network_interfaces = []

  # Description: The placement of the instance
  # Type: object
  # placement = null

  # Description: Determines whether a placement group is created & used by the node group
  # Type: bool
  # create_placement_group = false

  # Description: The options for the instance hostname. The default values are inherited from the subnet
  # Type: object
  # private_dns_name_options = null

  # Description: If true, the launched EC2 instance will be EBS-optimized
  # Type: bool
  # ebs_optimized = null

  # Description: The AMI from which to launch the instance
  # Type: string
  # ami_id = ""

  # Description: Type of Amazon Machine Image (AMI) associated with the node group. See the [AWS documentation](https://docs.aws.amazon.com/eks/latest/APIReference/API_Nodegroup.html#AmazonEKS-Type-Nodegroup-amiType) for valid values
  # Type: string
  # ami_type = "AL2023_x86_64_STANDARD"

  # Description: Kubernetes cluster version - used to lookup default AMI ID if one is not provided
  # Type: string
  # kubernetes_version = null

  # Description: The attribute requirements for the type of instance. If present then `instance_type` cannot be present
  # Type: object
  # instance_requirements = null

  # Description: The type of the instance to launch
  # Type: string
  # instance_type = "m6i.large"

  # Description: The key name that should be used for the instance
  # Type: string
  # key_name = null

  # Description: A list of security group IDs to associate
  # Type: list
  # vpc_security_group_ids = []

  # Description: The ID of the EKS cluster primary security group to associate with the instance(s). This is the security group that is automatically created by the EKS service
  # Type: string
  # cluster_primary_security_group_id = null

  # Description: Enables/disables detailed monitoring
  # Type: bool
  # enable_monitoring = false

  # Description: Determines whether to enable Elastic Fabric Adapter (EFA) support
  # Type: bool
  # enable_efa_support = false

  # Description: Determines whether to enable EFA (`false`, default) or EFA and EFA-only (`true`) network interfaces. Note: requires vpc-cni version `v1.18.4` or later
  # Type: bool
  # enable_efa_only = true

  # Description: The indices of the network interfaces that should be EFA-enabled. Only valid when `enable_efa_support` = `true`
  # Type: list
  # efa_indices = [0]

  # Description: Customize the metadata options for the instance
  # Type: object
  # metadata_options = {"http_endpoint":"enabled","http_put_response_hop_limit":1,"http_tokens":"required"}

  # Description: A map of additional tags to add to the tag_specifications of launch template created
  # Type: map
  # launch_template_tags = {}

  # Description: The tags to apply to the resources during launch
  # Type: list
  # tag_specifications = ["instance","volume","network-interface"]

  # Description: Determines whether to create autoscaling group or not
  # Type: bool
  # create_autoscaling_group = true

  # Description: Name of the Self managed Node Group
  # Type: string
  # name = ""

  # Description: Determines whether to use `name` as is or create a unique name beginning with the `name` as the prefix
  # Type: bool
  # use_name_prefix = true

  # Description: Launch template version. Can be version number, `$Latest`, or `$Default`
  # Type: string
  # launch_template_version = null

  # Description: A list of one or more availability zones for the group. Used for EC2-Classic and default subnets when not specified with `subnet_ids` argument. Conflicts with `subnet_ids`
  # Type: list
  # availability_zones = null

  # Description: A list of subnet IDs to launch resources in. Subnets automatically determine which availability zones the group will reside. Conflicts with `availability_zones`
  # Type: list
  # subnet_ids = null

  # Description: The minimum size of the autoscaling group
  # Type: number
  # min_size = 1

  # Description: The maximum size of the autoscaling group
  # Type: number
  # max_size = 3

  # Description: The number of Amazon EC2 instances that should be running in the autoscaling group
  # Type: number
  # desired_size = 1

  # Description: The unit of measurement for the value specified for `desired_size`. Supported for attribute-based instance type selection only. Valid values: `units`, `vcpu`, `memory-mib`
  # Type: string
  # desired_size_type = null

  # Description: Whether to ignore failed Auto Scaling scaling activities while waiting for capacity
  # Type: bool
  # ignore_failed_scaling_activities = null

  # Description: Reserved
  # Type: string
  # context = null

  # Description: Indicates whether capacity rebalance is enabled
  # Type: bool
  # capacity_rebalance = null

  # Description: Amount of time, in seconds, until a newly launched instance can contribute to the Amazon CloudWatch metrics. This delay lets an instance finish initializing before Amazon EC2 Auto Scaling aggregates instance metrics, resulting in more reliable usage data
  # Type: number
  # default_instance_warmup = null

  # Description: Allows setting instance protection. The autoscaling group will not select instances with this setting for termination during scale in events
  # Type: bool
  # protect_from_scale_in = false

  # Description: The name of the placement group into which you'll launch your instances
  # Type: string
  # placement_group = null

  # Description: `EC2` or `ELB`. Controls how health checking is done
  # Type: string
  # health_check_type = null

  # Description: Time (in seconds) after instance comes into service before checking health
  # Type: number
  # health_check_grace_period = null

  # Description: Allows deleting the Auto Scaling Group without waiting for all instances in the pool to terminate. You can force an Auto Scaling Group to delete even if it's in the process of scaling a resource. Normally, Terraform drains all the instances before deleting the group. This bypasses that behavior and potentially leaves resources dangling
  # Type: bool
  # force_delete = null

  # Description: A list of policies to decide how the instances in the Auto Scaling Group should be terminated. The allowed values are `OldestInstance`, `NewestInstance`, `OldestLaunchConfiguration`, `ClosestToNextInstanceHour`, `OldestLaunchTemplate`, `AllocationStrategy`, `Default`
  # Type: list
  # termination_policies = []

  # Description: A list of processes to suspend for the Auto Scaling Group. The allowed values are `Launch`, `Terminate`, `HealthCheck`, `ReplaceUnhealthy`, `AZRebalance`, `AlarmNotification`, `ScheduledActions`, `AddToLoadBalancer`. Note that if you suspend either the `Launch` or `Terminate` process types, it can prevent your Auto Scaling Group from functioning properly
  # Type: list
  # suspended_processes = []

  # Description: The maximum amount of time, in seconds, that an instance can be in service, values must be either equal to 0 or between 604800 and 31536000 seconds
  # Type: number
  # max_instance_lifetime = null

  # Description: A list of metrics to collect. The allowed values are `GroupDesiredCapacity`, `GroupInServiceCapacity`, `GroupPendingCapacity`, `GroupMinSize`, `GroupMaxSize`, `GroupInServiceInstances`, `GroupPendingInstances`, `GroupStandbyInstances`, `GroupStandbyCapacity`, `GroupTerminatingCapacity`, `GroupTerminatingInstances`, `GroupTotalCapacity`, `GroupTotalInstances`
  # Type: list
  # enabled_metrics = []

  # Description: The granularity to associate with the metrics to collect. The only valid value is `1Minute`
  # Type: string
  # metrics_granularity = null

  # Description: One or more Lifecycle Hooks to attach to the Auto Scaling Group before instances are launched. The syntax is exactly the same as the separate `aws_autoscaling_lifecycle_hook` resource, without the `autoscaling_group_name` attribute. Please note that this will only work when creating a new Auto Scaling Group. For all other use-cases, please use `aws_autoscaling_lifecycle_hook` resource
  # Type: list
  # initial_lifecycle_hooks = null

  # Description: If this block is configured, add a instance maintenance policy to the specified Auto Scaling group
  # Type: object
  # instance_maintenance_policy = null

  # Description: If this block is configured, start an Instance Refresh when this Auto Scaling Group is updated
  # Type: object
  # instance_refresh = {"preferences":{"min_healthy_percentage":66},"strategy":"Rolling"}

  # Description: Determines whether to use a mixed instances policy in the autoscaling group or not
  # Type: bool
  # use_mixed_instances_policy = false

  # Description: Configuration block containing settings to define launch targets for Auto Scaling groups
  # Type: object
  # mixed_instances_policy = null

  # Description: Timeout configurations for the autoscaling group
  # Type: object
  # timeouts = null

  # Description: A map of additional tags to add to the autoscaling group created. Tags are applied to the autoscaling group only and are NOT propagated to instances
  # Type: map
  # autoscaling_group_tags = {}

  # Description: Determines whether an IAM instance profile is created or to use an existing IAM instance profile
  # Type: bool
  # create_iam_instance_profile = true

  # Description: Amazon Resource Name (ARN) of an existing IAM instance profile that provides permissions for the node group. Required if `create_iam_instance_profile` = `false`
  # Type: string
  # iam_instance_profile_arn = null

  # Description: Name to use on IAM role created
  # Type: string
  # iam_role_name = null

  # Description: Determines whether cluster IAM role name (`iam_role_name`) is used as a prefix
  # Type: bool
  # iam_role_use_name_prefix = true

  # Description: IAM role path
  # Type: string
  # iam_role_path = null

  # Description: Description of the role
  # Type: string
  # iam_role_description = "Self managed node group IAM role"

  # Description: ARN of the policy that is used to set the permissions boundary for the IAM role
  # Type: string
  # iam_role_permissions_boundary = null

  # Description: Whether to attach the `AmazonEKS_CNI_Policy`/`AmazonEKS_CNI_IPv6_Policy` IAM policy to the IAM IAM role. WARNING: If set `false` the permissions must be assigned to the `aws-node` DaemonSet pods via another method or nodes will not be able to join the cluster
  # Type: bool
  # iam_role_attach_cni_policy = true

  # Description: Additional policies to be added to the IAM role
  # Type: map
  # iam_role_additional_policies = {}

  # Description: A map of additional tags to add to the IAM role created
  # Type: map
  # iam_role_tags = {}

  # Description: Determines whether an IAM role policy is created or not
  # Type: bool
  # create_iam_role_policy = true

  # Description: A list of IAM policy [statements](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#statement) - used for adding specific IAM permissions as needed
  # Type: list
  # iam_role_policy_statements = null

  # Description: Determines whether an access entry is created for the IAM role used by the node group
  # Type: bool
  # create_access_entry = true

  # Description: ARN of the IAM role used by the instance profile. Required when `create_access_entry = true` and `create_iam_instance_profile = false`
  # Type: string
  # iam_role_arn = null

  # Description: Determines if a security group is created
  # Type: bool
  # create_security_group = true

  # Description: Name to use on security group created
  # Type: string
  # security_group_name = null

  # Description: Determines whether the security group name (`security_group_name`) is used as a prefix
  # Type: bool
  # security_group_use_name_prefix = true

  # Description: Description of the security group created
  # Type: string
  # security_group_description = null

  # Description: Security group ingress rules to add to the security group created
  # Type: map
  # security_group_ingress_rules = {}

  # Description: Security group egress rules to add to the security group created
  # Type: map
  # security_group_egress_rules = {}

  # Description: A map of additional tags to add to the security group created
  # Type: map
  # security_group_tags = {}

  # Description: Determines whether to create EKS managed node group or not
  # Type: bool
  # create = true

  # Description: A map of tags to add to all resources
  # Type: map
  # tags = {}

  # Description: Region where the resource(s) will be managed. Defaults to the Region set in the provider configuration
  # Type: string
  # region = null

  # Description: The AWS partition - pass through value to reduce number of GET requests from data sources
  # Type: string
  # partition = ""

  # Description: The AWS account ID - pass through value to reduce number of GET requests from data sources
  # Type: string
  # account_id = ""

  # Description: Determines whether the bootstrap configurations are populated within the user data template. Only valid when using a custom AMI via `ami_id`
  # Type: bool
  # enable_bootstrap_user_data = false

  # Description: Name of associated EKS cluster
  # Type: string
  # cluster_name = ""

  # Description: Endpoint of associated EKS cluster
  # Type: string
  # cluster_endpoint = null

  # Description: Base64 encoded CA of associated EKS cluster
  # Type: string
  # cluster_auth_base64 = null

  # Description: The CIDR block (IPv4 or IPv6) used by the cluster to assign Kubernetes service IP addresses. This is derived from the cluster itself
  # Type: string
  # cluster_service_cidr = null

  # Description: User data that is injected into the user data script ahead of the EKS bootstrap script. Not used when `ami_type` = `BOTTLEROCKET_*`
  # Type: string
  # pre_bootstrap_user_data = null

  # Description: User data that is appended to the user data script after of the EKS bootstrap script. Not used when `ami_type` = `BOTTLEROCKET_*`
  # Type: string
  # post_bootstrap_user_data = null

  # Description: Additional arguments passed to the bootstrap script. When `ami_type` = `BOTTLEROCKET_*`; these are additional [settings](https://github.com/bottlerocket-os/bottlerocket#settings) that are provided to the Bottlerocket user data
  # Type: string
  # bootstrap_extra_args = null

  # Description: Path to a local, custom user data template file to use when rendering user data
  # Type: string
  # user_data_template_path = null

  # Description: Array of cloud-init document parts that are created before the nodeadm document part
  # Type: list
  # cloudinit_pre_nodeadm = null

  # Description: Array of cloud-init document parts that are created after the nodeadm document part
  # Type: list
  # cloudinit_post_nodeadm = null

  # Description: Determines whether to create a launch template or not. If set to `false`, EKS will use its own default launch template
  # Type: bool
  # create_launch_template = true

  # Description: Determines whether to use a custom launch template or not. If set to `false`, EKS will use its own default launch template
  # Type: bool
  # use_custom_launch_template = true

  # Description: The ID of an existing launch template to use. Required when `create_launch_template` = `false` and `use_custom_launch_template` = `true`
  # Type: string
  # launch_template_id = ""

  # Description: Name of launch template to be created
  # Type: string
  # launch_template_name = null

  # Description: Determines whether to use `launch_template_name` as is or create a unique name beginning with the `launch_template_name` as the prefix
  # Type: bool
  # launch_template_use_name_prefix = true

  # Description: Description of the launch template
  # Type: string
  # launch_template_description = null

  # Description: If true, the launched EC2 instance(s) will be EBS-optimized
  # Type: bool
  # ebs_optimized = null

  # Description: The AMI from which to launch the instance. If not supplied, EKS will use its own default image
  # Type: string
  # ami_id = ""

  # Description: The key name that should be used for the instance(s)
  # Type: string
  # key_name = null

  # Description: A list of security group IDs to associate
  # Type: list
  # vpc_security_group_ids = []

  # Description: The ID of the EKS cluster primary security group to associate with the instance(s). This is the security group that is automatically created by the EKS service
  # Type: string
  # cluster_primary_security_group_id = null

  # Description: Default version of the launch template
  # Type: string
  # launch_template_default_version = null

  # Description: Whether to update the launch templates default version on each update. Conflicts with `launch_template_default_version`
  # Type: bool
  # update_launch_template_default_version = true

  # Description: If true, enables EC2 instance termination protection
  # Type: bool
  # disable_api_termination = null

  # Description: The kernel ID
  # Type: string
  # kernel_id = null

  # Description: The ID of the ram disk
  # Type: string
  # ram_disk_id = null

  # Description: Specify volumes to attach to the instance besides the volumes specified by the AMI
  # Type: map
  # block_device_mappings = null

  # Description: Targeting for EC2 capacity reservations
  # Type: object
  # capacity_reservation_specification = null

  # Description: The CPU options for the instance
  # Type: object
  # cpu_options = null

  # Description: Customize the credit specification of the instance
  # Type: object
  # credit_specification = null

  # Description: Enable Nitro Enclaves on launched instances
  # Type: object
  # enclave_options = null

  # Description: The market (purchasing) option for the instance
  # Type: object
  # instance_market_options = null

  # Description: The maintenance options for the instance
  # Type: object
  # maintenance_options = null

  # Description: A list of license specifications to associate with
  # Type: list
  # license_specifications = null

  # Description: Customize the metadata options for the instance
  # Type: object
  # metadata_options = {"http_endpoint":"enabled","http_put_response_hop_limit":1,"http_tokens":"required"}

  # Description: Enables/disables detailed monitoring
  # Type: bool
  # enable_monitoring = false

  # Description: Determines whether to enable Elastic Fabric Adapter (EFA) support
  # Type: bool
  # enable_efa_support = false

  # Description: Determines whether to enable EFA (`false`, default) or EFA and EFA-only (`true`) network interfaces. Note: requires vpc-cni version `v1.18.4` or later
  # Type: bool
  # enable_efa_only = true

  # Description: The indices of the network interfaces that should be EFA-enabled. Only valid when `enable_efa_support` = `true`
  # Type: list
  # efa_indices = [0]

  # Description: Customize network interfaces to be attached at instance boot time
  # Type: list
  # network_interfaces = []

  # Description: The placement of the instance
  # Type: object
  # placement = null

  # Description: Determines whether a placement group is created & used by the node group
  # Type: bool
  # create_placement_group = false

  # Description: The options for the instance hostname. The default values are inherited from the subnet
  # Type: object
  # private_dns_name_options = null

  # Description: A map of additional tags to add to the tag_specifications of launch template created
  # Type: map
  # launch_template_tags = {}

  # Description: The tags to apply to the resources during launch
  # Type: list
  # tag_specifications = ["instance","volume","network-interface"]

  # Description: Identifiers of EC2 Subnets to associate with the EKS Node Group. These subnets must have the following resource tag: `kubernetes.io/cluster/CLUSTER_NAME`
  # Type: list
  # subnet_ids = null

  # Description: Minimum number of instances/nodes
  # Type: number
  # min_size = 1

  # Description: Maximum number of instances/nodes
  # Type: number
  # max_size = 3

  # Description: Desired number of instances/nodes
  # Type: number
  # desired_size = 1

  # Description: Name of the EKS managed node group
  # Type: string
  # name = ""

  # Description: Determines whether to use `name` as is or create a unique name beginning with the `name` as the prefix
  # Type: bool
  # use_name_prefix = true

  # Description: Type of Amazon Machine Image (AMI) associated with the EKS Node Group. See the [AWS documentation](https://docs.aws.amazon.com/eks/latest/APIReference/API_Nodegroup.html#AmazonEKS-Type-Nodegroup-amiType) for valid values
  # Type: string
  # ami_type = "AL2023_x86_64_STANDARD"

  # Description: The AMI version. Defaults to latest AMI release version for the given Kubernetes version and AMI type
  # Type: string
  # ami_release_version = null

  # Description: Determines whether to use the latest AMI release version for the given `ami_type` (except for `CUSTOM`). Note: `ami_type` and `kubernetes_version` must be supplied in order to enable this feature
  # Type: bool
  # use_latest_ami_release_version = true

  # Description: Type of capacity associated with the EKS Node Group. Valid values: `ON_DEMAND`, `SPOT`
  # Type: string
  # capacity_type = "ON_DEMAND"

  # Description: Disk size in GiB for nodes. Defaults to `20`. Only valid when `use_custom_launch_template` = `false`
  # Type: number
  # disk_size = null

  # Description: Force version update if existing pods are unable to be drained due to a pod disruption budget issue
  # Type: bool
  # force_update_version = null

  # Description: Set of instance types associated with the EKS Node Group. Defaults to `["t3.medium"]`
  # Type: list
  # instance_types = null

  # Description: Key-value map of Kubernetes labels. Only labels that are applied with the EKS API are managed by this argument. Other Kubernetes labels applied to the EKS Node Group will not be managed
  # Type: map
  # labels = null

  # Description: Kubernetes version. Defaults to EKS Cluster Kubernetes version
  # Type: string
  # kubernetes_version = null

  # Description: Launch template version number. The default is `$Default`
  # Type: string
  # launch_template_version = null

  # Description: Configuration block with remote access settings. Only valid when `use_custom_launch_template` = `false`
  # Type: object
  # remote_access = null

  # Description: The Kubernetes taints to be applied to the nodes in the node group. Maximum of 50 taints per node group
  # Type: map
  # taints = null

  # Description: Configuration block of settings for max unavailable resources during node group updates
  # Type: object
  # update_config = {"max_unavailable_percentage":33}

  # Description: The node auto repair configuration for the node group
  # Type: object
  # node_repair_config = null

  # Description: Create, update, and delete timeout configurations for the node group
  # Type: object
  # timeouts = null

  # Description: Determines whether an IAM role is created or to use an existing IAM role
  # Type: bool
  # create_iam_role = true

  # Description: The IP family used to assign Kubernetes pod and service addresses. Valid values are `ipv4` (default) and `ipv6`
  # Type: string
  # cluster_ip_family = "ipv4"

  # Description: Existing IAM role ARN for the node group. Required if `create_iam_role` is set to `false`
  # Type: string
  # iam_role_arn = null

  # Description: Name to use on IAM role created
  # Type: string
  # iam_role_name = null

  # Description: Determines whether the IAM role name (`iam_role_name`) is used as a prefix
  # Type: bool
  # iam_role_use_name_prefix = true

  # Description: IAM role path
  # Type: string
  # iam_role_path = null

  # Description: Description of the role
  # Type: string
  # iam_role_description = "EKS managed node group IAM role"

  # Description: ARN of the policy that is used to set the permissions boundary for the IAM role
  # Type: string
  # iam_role_permissions_boundary = null

  # Description: Whether to attach the `AmazonEKS_CNI_Policy`/`AmazonEKS_CNI_IPv6_Policy` IAM policy to the IAM IAM role. WARNING: If set `false` the permissions must be assigned to the `aws-node` DaemonSet pods via another method or nodes will not be able to join the cluster
  # Type: bool
  # iam_role_attach_cni_policy = true

  # Description: Additional policies to be added to the IAM role
  # Type: map
  # iam_role_additional_policies = {}

  # Description: A map of additional tags to add to the IAM role created
  # Type: map
  # iam_role_tags = {}

  # Description: Determines whether an IAM role policy is created or not
  # Type: bool
  # create_iam_role_policy = true

  # Description: A list of IAM policy [statements](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#statement) - used for adding specific IAM permissions as needed
  # Type: list
  # iam_role_policy_statements = null

  # Description: Determines if a security group is created
  # Type: bool
  # create_security_group = true

  # Description: Name to use on security group created
  # Type: string
  # security_group_name = null

  # Description: Determines whether the security group name (`security_group_name`) is used as a prefix
  # Type: bool
  # security_group_use_name_prefix = true

  # Description: Description of the security group created
  # Type: string
  # security_group_description = null

  # Description: Security group ingress rules to add to the security group created
  # Type: map
  # security_group_ingress_rules = {}

  # Description: Security group egress rules to add to the security group created
  # Type: map
  # security_group_egress_rules = {}

  # Description: A map of additional tags to add to the security group created
  # Type: map
  # security_group_tags = {}

  # Description: Determines whether to create Fargate profile or not
  # Type: bool
  # create = true

  # Description: A map of tags to add to all resources
  # Type: map
  # tags = {}

  # Description: Region where the resource(s) will be managed. Defaults to the Region set in the provider configuration
  # Type: string
  # region = null

  # Description: The AWS partition - pass through value to reduce number of GET requests from data sources
  # Type: string
  # partition = ""

  # Description: The AWS account ID - pass through value to reduce number of GET requests from data sources
  # Type: string
  # account_id = ""

  # Description: Determines whether an IAM role is created or to use an existing IAM role
  # Type: bool
  # create_iam_role = true

  # Description: The IP family used to assign Kubernetes pod and service addresses. Valid values are `ipv4` (default) and `ipv6`
  # Type: string
  # cluster_ip_family = "ipv4"

  # Description: Existing IAM role ARN for the Fargate profile. Required if `create_iam_role` is set to `false`
  # Type: string
  # iam_role_arn = null

  # Description: Name to use on IAM role created
  # Type: string
  # iam_role_name = ""

  # Description: Determines whether the IAM role name (`iam_role_name`) is used as a prefix
  # Type: bool
  # iam_role_use_name_prefix = true

  # Description: IAM role path
  # Type: string
  # iam_role_path = null

  # Description: Description of the role
  # Type: string
  # iam_role_description = "Fargate profile IAM role"

  # Description: ARN of the policy that is used to set the permissions boundary for the IAM role
  # Type: string
  # iam_role_permissions_boundary = null

  # Description: Whether to attach the `AmazonEKS_CNI_Policy`/`AmazonEKS_CNI_IPv6_Policy` IAM policy to the IAM IAM role. WARNING: If set `false` the permissions must be assigned to the `aws-node` DaemonSet pods via another method or nodes will not be able to join the cluster
  # Type: bool
  # iam_role_attach_cni_policy = true

  # Description: Additional policies to be added to the IAM role
  # Type: map
  # iam_role_additional_policies = {}

  # Description: A map of additional tags to add to the IAM role created
  # Type: map
  # iam_role_tags = {}

  # Description: Determines whether an IAM role policy is created or not
  # Type: bool
  # create_iam_role_policy = true

  # Description: A list of IAM policy [statements](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#statement) - used for adding specific IAM permissions as needed
  # Type: list
  # iam_role_policy_statements = null

  # Description: Name of the EKS cluster
  # Type: string
  # cluster_name = ""

  # Description: Name of the EKS Fargate Profile
  # Type: string
  # name = ""

  # Description: A list of subnet IDs for the EKS Fargate Profile
  # Type: list
  # subnet_ids = []

  # Description: Configuration block(s) for selecting Kubernetes Pods to execute with this Fargate Profile
  # Type: list
  # selectors = null

  # Description: Create and delete timeout configurations for the Fargate Profile
  # Type: object
  # timeouts = null

  # Description: Controls if resources should be created (affects nearly all resources)
  # Type: bool
  # create = true

  # Description: A map of tags to add to all resources
  # Type: map
  # tags = {}

  # Description: The name of the EKS cluster
  # Type: string
  # cluster_name = ""

  # Description: Region where the resource(s) will be managed. Defaults to the Region set in the provider configuration
  # Type: string
  # region = null

  # Description: Determines whether an IAM role is created
  # Type: bool
  # create_iam_role = true

  # Description: Determines whether the controller policy is created as a standard IAM policy or inline IAM policy. This can be enabled when the error `LimitExceeded: Cannot exceed quota for PolicySize: 6144` is received since standard IAM policies have a limit of 6,144 characters versus an inline role policy's limit of 10,240 ([Reference](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html))
  # Type: bool
  # enable_inline_policy = false

  # Description: Name of the IAM role
  # Type: string
  # iam_role_name = "KarpenterController"

  # Description: Determines whether the name of the IAM role (`iam_role_name`) is used as a prefix
  # Type: bool
  # iam_role_use_name_prefix = true

  # Description: Path of the IAM role
  # Type: string
  # iam_role_path = "/"

  # Description: IAM role description
  # Type: string
  # iam_role_description = "Karpenter controller IAM role"

  # Description: Maximum API session duration in seconds between 3600 and 43200
  # Type: number
  # iam_role_max_session_duration = null

  # Description: Permissions boundary ARN to use for the IAM role
  # Type: string
  # iam_role_permissions_boundary_arn = null

  # Description: A map of additional tags to add the the IAM role
  # Type: map
  # iam_role_tags = {}

  # Description: Name of the IAM policy
  # Type: string
  # iam_policy_name = "KarpenterController"

  # Description: Determines whether the name of the IAM policy (`iam_policy_name`) is used as a prefix
  # Type: bool
  # iam_policy_use_name_prefix = true

  # Description: Path of the IAM policy
  # Type: string
  # iam_policy_path = "/"

  # Description: IAM policy description
  # Type: string
  # iam_policy_description = "Karpenter controller IAM policy"

  # Description: A list of IAM policy documents to override the default assume role policy document for the Karpenter controller IAM role
  # Type: list
  # iam_role_override_assume_policy_documents = []

  # Description: A list of IAM policy documents to use as a source for the assume role policy document for the Karpenter controller IAM role
  # Type: list
  # iam_role_source_assume_policy_documents = []

  # Description: A list of IAM policy [statements](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#statement) - used for adding specific IAM permissions as needed
  # Type: list
  # iam_policy_statements = null

  # Description: Policies to attach to the IAM role in `{'static_name' = 'policy_arn'}` format
  # Type: map
  # iam_role_policies = {}

  # Description: List of SSM Parameter ARNs that Karpenter controller is allowed read access (for retrieving AMI IDs)
  # Type: list
  # ami_id_ssm_parameter_arns = []

  # Description: Determines whether to create pod identity association
  # Type: bool
  # create_pod_identity_association = true

  # Description: Namespace to associate with the Karpenter Pod Identity
  # Type: string
  # namespace = "kube-system"

  # Description: Service account to associate with the Karpenter Pod Identity
  # Type: string
  # service_account = "karpenter"

  # Description: Determines whether to enable native spot termination handling
  # Type: bool
  # enable_spot_termination = true

  # Description: Name of the SQS queue
  # Type: string
  # queue_name = null

  # Description: Boolean to enable server-side encryption (SSE) of message content with SQS-owned encryption keys
  # Type: bool
  # queue_managed_sse_enabled = true

  # Description: The ID of an AWS-managed customer master key (CMK) for Amazon SQS or a custom CMK
  # Type: string
  # queue_kms_master_key_id = null

  # Description: The length of time, in seconds, for which Amazon SQS can reuse a data key to encrypt or decrypt messages before calling AWS KMS again
  # Type: number
  # queue_kms_data_key_reuse_period_seconds = null

  # Description: A list of IAM policy [statements](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#statement) - used for adding specific SQS queue policy permissions as needed
  # Type: map
  # queue_policy_statements = null

  # Description: Determines whether an IAM role is created or to use an existing IAM role
  # Type: bool
  # create_node_iam_role = true

  # Description: The IP family used to assign Kubernetes pod and service addresses. Valid values are `ipv4` (default) and `ipv6`. Note: If `ipv6` is specified, the `AmazonEKS_CNI_IPv6_Policy` must exist in the account. This policy is created by the EKS module with `create_cni_ipv6_iam_policy = true`
  # Type: string
  # cluster_ip_family = "ipv4"

  # Description: Existing IAM role ARN for the IAM instance profile. Required if `create_iam_role` is set to `false`
  # Type: string
  # node_iam_role_arn = null

  # Description: Name to use on IAM role created
  # Type: string
  # node_iam_role_name = null

  # Description: Determines whether the Node IAM role name (`node_iam_role_name`) is used as a prefix
  # Type: bool
  # node_iam_role_use_name_prefix = true

  # Description: IAM role path
  # Type: string
  # node_iam_role_path = "/"

  # Description: Description of the role
  # Type: string
  # node_iam_role_description = null

  # Description: Maximum API session duration in seconds between 3600 and 43200
  # Type: number
  # node_iam_role_max_session_duration = null

  # Description: ARN of the policy that is used to set the permissions boundary for the IAM role
  # Type: string
  # node_iam_role_permissions_boundary = null

  # Description: Whether to attach the `AmazonEKS_CNI_Policy`/`AmazonEKS_CNI_IPv6_Policy` IAM policy to the IAM IAM role. WARNING: If set `false` the permissions must be assigned to the `aws-node` DaemonSet pods via another method or nodes will not be able to join the cluster
  # Type: bool
  # node_iam_role_attach_cni_policy = true

  # Description: Additional policies to be added to the IAM role
  # Type: map
  # node_iam_role_additional_policies = {}

  # Description: A map of additional tags to add to the IAM role created
  # Type: map
  # node_iam_role_tags = {}

  # Description: Determines whether an access entry is created for the IAM role used by the node IAM role
  # Type: bool
  # create_access_entry = true

  # Description: Type of the access entry. `EC2_LINUX`, `FARGATE_LINUX`, or `EC2_WINDOWS`; defaults to `EC2_LINUX`
  # Type: string
  # access_entry_type = "EC2_LINUX"

  # Description: Whether to create an IAM instance profile
  # Type: bool
  # create_instance_profile = false

  # Description: Prefix used for all event bridge rules
  # Type: string
  # rule_name_prefix = "Karpenter"

}
