
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/terraform-aws-modules/terraform-aws-iam.git//modules/iam-role-for-service-accounts?ref=v6.2.3"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Controls if resources should be created (affects all resources)
  # Type: bool
  # create = true

  # Description: Region where *select resource(s) will be managed (IAM resources are global). Defaults to the Region set in the provider configuration
  # Type: string
  # region = null

  # Description: A map of tags to add to all resources
  # Type: map
  # tags = {}

  # Description: Name to use on IAM role created
  # Type: string
  # name = ""

  # Description: Determines whether the IAM role/policy name (`name`/`policy_name`) is used as a prefix
  # Type: bool
  # use_name_prefix = true

  # Description: Path of IAM role
  # Type: string
  # path = "/"

  # Description: Description of the role
  # Type: string
  # description = null

  # Description: Maximum session duration (in seconds) that you want to set for the specified role. If you do not specify a value for this setting, the default maximum of one hour is applied. This setting can have a value from 1 hour to 12 hours
  # Type: number
  # max_session_duration = null

  # Description: ARN of the policy that is used to set the permissions boundary for the IAM role
  # Type: string
  # permissions_boundary = null

  # Description: Name of the [IAM condition operator](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html) to evaluate when assuming the role
  # Type: string
  # trust_condition_test = "StringEquals"

  # Description: Map of OIDC providers where each provider map should contain the `provider`, `provider_arn`, and `namespace_service_accounts`
  # Type: any
  # oidc_providers = {}

  # Description: Policies to attach to the IAM role in `{'static_name' = 'policy_arn'}` format
  # Type: map
  # policies = {}

  # Description: Whether to create an IAM policy that is attached to the IAM role created
  # Type: bool
  # create_policy = true

  # Description: List of IAM policy documents that are merged together into the exported document. Statements must have unique `sid`s
  # Type: list
  # source_policy_documents = []

  # Description: List of IAM policy documents that are merged together into the exported document. In merging, statements with non-blank `sid`s will override statements with the same `sid`
  # Type: list
  # override_policy_documents = []

  # Description: A map of IAM policy [statements](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#statement) for custom permission usage
  # Type: map
  # permissions = null

  # Description: Name to use on IAM policy created
  # Type: string
  # policy_name = null

  # Description: Path of IAM policy
  # Type: string
  # policy_path = null

  # Description: IAM policy description
  # Type: string
  # policy_description = null

  # Description: Determines whether to attach the AWS Gateway Controller IAM policy to the role
  # Type: bool
  # attach_aws_gateway_controller_policy = false

  # Description: Determines whether to attach the Cert Manager IAM policy to the role
  # Type: bool
  # attach_cert_manager_policy = false

  # Description: Route53 hosted zone ARNs to allow Cert manager to manage records
  # Type: list
  # cert_manager_hosted_zone_arns = []

  # Description: Determines whether to attach the Cluster Autoscaler IAM policy to the role
  # Type: bool
  # attach_cluster_autoscaler_policy = false

  # Description: List of cluster names to appropriately scope permissions within the Cluster Autoscaler IAM policy
  # Type: list
  # cluster_autoscaler_cluster_names = []

  # Description: Determines whether to attach the EBS CSI IAM policy to the role
  # Type: bool
  # attach_ebs_csi_policy = false

  # Description: KMS CMK ARNs to allow EBS CSI to manage encrypted volumes
  # Type: list
  # ebs_csi_kms_cmk_arns = []

  # Description: Determines whether to attach the Mountpoint S3 CSI IAM policy to the role
  # Type: bool
  # attach_mountpoint_s3_csi_policy = false

  # Description: S3 bucket ARNs to allow Mountpoint S3 CSI to list buckets
  # Type: list
  # mountpoint_s3_csi_bucket_arns = []

  # Description: KMS Key ARNs to allow Mountpoint S3 CSI driver to download and upload Objects of a S3 bucket using `aws:kms` SSE
  # Type: list
  # mountpoint_s3_csi_kms_arns = []

  # Description: S3 path ARNs to allow Mountpoint S3 CSI driver to manage items at the provided path(s). This is required if `attach_mountpoint_s3_csi_policy = true`
  # Type: list
  # mountpoint_s3_csi_path_arns = []

  # Description: Determines whether to attach the EFS CSI IAM policy to the role
  # Type: bool
  # attach_efs_csi_policy = false

  # Description: Determines whether to attach the External DNS IAM policy to the role
  # Type: bool
  # attach_external_dns_policy = false

  # Description: Route53 hosted zone ARNs to allow External DNS to manage records
  # Type: list
  # external_dns_hosted_zone_arns = []

  # Description: Determines whether to attach the External Secrets policy to the role
  # Type: bool
  # attach_external_secrets_policy = false

  # Description: List of Systems Manager Parameter ARNs that contain secrets to mount using External Secrets
  # Type: list
  # external_secrets_ssm_parameter_arns = []

  # Description: List of Secrets Manager ARNs that contain secrets to mount using External Secrets
  # Type: list
  # external_secrets_secrets_manager_arns = []

  # Description: List of KMS Key ARNs that are used by Secrets Manager that contain secrets to mount using External Secrets
  # Type: list
  # external_secrets_kms_key_arns = []

  # Description: Determines whether External Secrets may use secretsmanager:CreateSecret
  # Type: bool
  # external_secrets_secrets_manager_create_permission = false

  # Description: Determines whether to attach the FSx for Lustre CSI Driver IAM policy to the role
  # Type: bool
  # attach_fsx_lustre_csi_policy = false

  # Description: Service role ARNs to allow FSx for Lustre CSI create and manage FSX for Lustre service linked roles
  # Type: list
  # fsx_lustre_csi_service_role_arns = ["arn:aws:iam::*:role/aws-service-role/s3.data-source.lustre.fsx.amazonaws.com/*"]

  # Description: Determines whether to attach the FSx for OpenZFS CSI Driver IAM policy to the role
  # Type: bool
  # attach_fsx_openzfs_csi_policy = false

  # Description: Service role ARNs to allow FSx for OpenZFS CSI create and manage FSX for openzfs service linked roles
  # Type: list
  # fsx_openzfs_csi_service_role_arns = ["arn:aws:iam::*:role/aws-service-role/fsx.amazonaws.com/*"]

  # Description: Determines whether to attach the Load Balancer Controller policy to the role
  # Type: bool
  # attach_load_balancer_controller_policy = false

  # Description: Determines whether to attach the Load Balancer Controller policy for the TargetGroupBinding only
  # Type: bool
  # attach_load_balancer_controller_targetgroup_binding_only_policy = false

  # Description: List of Target groups ARNs using Load Balancer Controller
  # Type: list
  # load_balancer_controller_targetgroup_arns = []

  # Description: Determines whether to attach the Amazon Managed Service for Prometheus IAM policy to the role
  # Type: bool
  # attach_amazon_managed_service_prometheus_policy = false

  # Description: List of AMP Workspace ARNs to read and write metrics
  # Type: list
  # amazon_managed_service_prometheus_workspace_arns = []

  # Description: Determines whether to attach the Velero IAM policy to the role
  # Type: bool
  # attach_velero_policy = false

  # Description: List of S3 Bucket ARNs that Velero needs access to in order to backup and restore cluster resources
  # Type: list
  # velero_s3_bucket_arns = []

  # Description: Determines whether to attach the VPC CNI IAM policy to the role
  # Type: bool
  # attach_vpc_cni_policy = false

  # Description: Determines whether to enable VPC CNI permission to create CloudWatch Log groups and publish network policy events
  # Type: bool
  # vpc_cni_enable_cloudwatch_logs = false

  # Description: Determines whether to enable IPv4 permissions for VPC CNI policy
  # Type: bool
  # vpc_cni_enable_ipv4 = false

  # Description: Determines whether to enable IPv6 permissions for VPC CNI policy
  # Type: bool
  # vpc_cni_enable_ipv6 = false

  # Description: Determines whether to attach the Node Termination Handler policy to the role
  # Type: bool
  # attach_node_termination_handler_policy = false

  # Description: List of SQS ARNs that contain node termination events
  # Type: list
  # node_termination_handler_sqs_queue_arns = []

  # Description: Determines whether to attach the Amazon CloudWatch Observability IAM policies to the role
  # Type: bool
  # attach_cloudwatch_observability_policy = false

  # Description: Determines whether to create an inline policy
  # Type: bool
  # create_inline_policy = false

  # Description: List of IAM policy documents that are merged together into the exported document. Statements must have unique `sid`s
  # Type: list
  # source_inline_policy_documents = []

  # Description: List of IAM policy documents that are merged together into the exported document. In merging, statements with non-blank `sid`s will override statements with the same `sid`
  # Type: list
  # override_inline_policy_documents = []

  # Description: A map of IAM policy [statements](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#statement) for inline policy permissions
  # Type: map
  # inline_policy_permissions = null

}
