
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/terraform-module/terraform-helm-release.git?ref=v2.9.1"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: namespace where to deploy an application
  # Type: string
  namespace = "" # TODO: fill in value

  # Description: an application to deploy
  # Type: map
  app = {} # TODO: fill in value

  # Description: Helm repository
  # Type: string
  repository = "" # TODO: fill in value


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: repository configuration
  # Type: map
  # repository_config = {}

  # Description: Extra values
  # Type: list
  # values = []

  # Description: Value block with custom STRING values to be merged with the values yaml.
  # Type: list
  # set = null

  # Description: Value block with custom sensitive values to be merged with the values yaml that won't be exposed in the plan's diff.
  # Type: list
  # set_sensitive = null

}
