
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/terraform-aws-modules/terraform-aws-vpc.git?ref=v6.5.1"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Controls if VPC should be created (it affects almost all resources)
  # Type: bool
  # create_vpc = true

  # Description: Region where the resource(s) will be managed. Defaults to the region set in the provider configuration
  # Type: string
  # region = null

  # Description: A map of tags to add to all resources
  # Type: map
  # tags = {}

  # Description: Name to be used on all the resources as identifier
  # Type: string
  # name = ""

  # Description: (Optional) The IPv4 CIDR block for the VPC. CIDR can be explicitly set or it can be derived from IPAM using `ipv4_netmask_length` & `ipv4_ipam_pool_id`
  # Type: string
  # cidr = "10.0.0.0/16"

  # Description: List of secondary CIDR blocks to associate with the VPC to extend the IP Address pool
  # Type: list
  # secondary_cidr_blocks = []

  # Description: A tenancy option for instances launched into the VPC
  # Type: string
  # instance_tenancy = "default"

  # Description: A list of availability zones names or ids in the region
  # Type: list
  # azs = []

  # Description: Should be true to enable DNS hostnames in the VPC
  # Type: bool
  # enable_dns_hostnames = true

  # Description: Should be true to enable DNS support in the VPC
  # Type: bool
  # enable_dns_support = true

  # Description: Determines whether network address usage metrics are enabled for the VPC
  # Type: bool
  # enable_network_address_usage_metrics = null

  # Description: Determines whether IPAM pool is used for CIDR allocation
  # Type: bool
  # use_ipam_pool = false

  # Description: (Optional) The ID of an IPv4 IPAM pool you want to use for allocating this VPC's CIDR
  # Type: string
  # ipv4_ipam_pool_id = null

  # Description: (Optional) The netmask length of the IPv4 CIDR you want to allocate to this VPC. Requires specifying a ipv4_ipam_pool_id
  # Type: number
  # ipv4_netmask_length = null

  # Description: Requests an Amazon-provided IPv6 CIDR block with a /56 prefix length for the VPC. You cannot specify the range of IP addresses, or the size of the CIDR block
  # Type: bool
  # enable_ipv6 = false

  # Description: (Optional) IPv6 CIDR block to request from an IPAM Pool. Can be set explicitly or derived from IPAM using `ipv6_netmask_length`
  # Type: string
  # ipv6_cidr = null

  # Description: (Optional) IPAM Pool ID for a IPv6 pool. Conflicts with `assign_generated_ipv6_cidr_block`
  # Type: string
  # ipv6_ipam_pool_id = null

  # Description: (Optional) Netmask length to request from IPAM Pool. Conflicts with `ipv6_cidr_block`. This can be omitted if IPAM pool as a `allocation_default_netmask_length` set. Valid values: `56`
  # Type: number
  # ipv6_netmask_length = null

  # Description: By default when an IPv6 CIDR is assigned to a VPC a default ipv6_cidr_block_network_border_group will be set to the region of the VPC. This can be changed to restrict advertisement of public addresses to specific Network Border Groups such as LocalZones
  # Type: string
  # ipv6_cidr_block_network_border_group = null

  # Description: Additional tags for the VPC
  # Type: map
  # vpc_tags = {}

  # Description: A map of VPC block public access options
  # Type: map
  # vpc_block_public_access_options = {}

  # Description: A map of VPC block public access exclusions
  # Type: map
  # vpc_block_public_access_exclusions = {}

  # Description: Should be true if you want to specify a DHCP options set with a custom domain name, DNS servers, NTP servers, netbios servers, and/or netbios server type
  # Type: bool
  # enable_dhcp_options = false

  # Description: Specifies DNS name for DHCP options set (requires enable_dhcp_options set to true)
  # Type: string
  # dhcp_options_domain_name = ""

  # Description: Specify a list of DNS server addresses for DHCP options set, default to AWS provided (requires enable_dhcp_options set to true)
  # Type: list
  # dhcp_options_domain_name_servers = ["AmazonProvidedDNS"]

  # Description: Specify a list of NTP servers for DHCP options set (requires enable_dhcp_options set to true)
  # Type: list
  # dhcp_options_ntp_servers = []

  # Description: Specify a list of netbios servers for DHCP options set (requires enable_dhcp_options set to true)
  # Type: list
  # dhcp_options_netbios_name_servers = []

  # Description: Specify netbios node_type for DHCP options set (requires enable_dhcp_options set to true)
  # Type: string
  # dhcp_options_netbios_node_type = ""

  # Description: How frequently, in seconds, a running instance with an IPv6 assigned to it goes through DHCPv6 lease renewal (requires enable_dhcp_options set to true)
  # Type: number
  # dhcp_options_ipv6_address_preferred_lease_time = null

  # Description: Additional tags for the DHCP option set (requires enable_dhcp_options set to true)
  # Type: map
  # dhcp_options_tags = {}

  # Description: A list of public subnets inside the VPC
  # Type: list
  # public_subnets = []

  # Description: Specify true to indicate that network interfaces created in the specified subnet should be assigned an IPv6 address. Default is `false`
  # Type: bool
  # public_subnet_assign_ipv6_address_on_creation = false

  # Description: Indicates whether DNS queries made to the Amazon-provided DNS Resolver in this subnet should return synthetic IPv6 addresses for IPv4-only destinations. Default: `true`
  # Type: bool
  # public_subnet_enable_dns64 = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS AAAA records. Default: `true`
  # Type: bool
  # public_subnet_enable_resource_name_dns_aaaa_record_on_launch = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS A records. Default: `false`
  # Type: bool
  # public_subnet_enable_resource_name_dns_a_record_on_launch = false

  # Description: Indicates whether to create a separate route table for each public subnet. Default: `false`
  # Type: bool
  # create_multiple_public_route_tables = false

  # Description: Assigns IPv6 public subnet id based on the Amazon provided /56 prefix base 10 integer (0-256). Must be of equal length to the corresponding IPv4 subnet list
  # Type: list
  # public_subnet_ipv6_prefixes = []

  # Description: Indicates whether to create an IPv6-only subnet. Default: `false`
  # Type: bool
  # public_subnet_ipv6_native = false

  # Description: Specify true to indicate that instances launched into the subnet should be assigned a public IP address. Default is `false`
  # Type: bool
  # map_public_ip_on_launch = false

  # Description: The type of hostnames to assign to instances in the subnet at launch. For IPv6-only subnets, an instance DNS name must be based on the instance ID. For dual-stack and IPv4-only subnets, you can specify whether DNS names use the instance IPv4 address or the instance ID. Valid values: `ip-name`, `resource-name`
  # Type: string
  # public_subnet_private_dns_hostname_type_on_launch = null

  # Description: Explicit values to use in the Name tag on public subnets. If empty, Name tags are generated
  # Type: list
  # public_subnet_names = []

  # Description: Suffix to append to public subnets name
  # Type: string
  # public_subnet_suffix = "public"

  # Description: Additional tags for the public subnets
  # Type: map
  # public_subnet_tags = {}

  # Description: Additional tags for the public subnets where the primary key is the AZ
  # Type: map
  # public_subnet_tags_per_az = {}

  # Description: Additional tags for the public route tables
  # Type: map
  # public_route_table_tags = {}

  # Description: Whether to use dedicated network ACL (not default) and custom rules for public subnets
  # Type: bool
  # public_dedicated_network_acl = false

  # Description: Public subnets inbound network ACLs
  # Type: list
  # public_inbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Public subnets outbound network ACLs
  # Type: list
  # public_outbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Additional tags for the public subnets network ACL
  # Type: map
  # public_acl_tags = {}

  # Description: A list of private subnets inside the VPC
  # Type: list
  # private_subnets = []

  # Description: Specify true to indicate that network interfaces created in the specified subnet should be assigned an IPv6 address. Default is `false`
  # Type: bool
  # private_subnet_assign_ipv6_address_on_creation = false

  # Description: Indicates whether DNS queries made to the Amazon-provided DNS Resolver in this subnet should return synthetic IPv6 addresses for IPv4-only destinations. Default: `true`
  # Type: bool
  # private_subnet_enable_dns64 = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS AAAA records. Default: `true`
  # Type: bool
  # private_subnet_enable_resource_name_dns_aaaa_record_on_launch = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS A records. Default: `false`
  # Type: bool
  # private_subnet_enable_resource_name_dns_a_record_on_launch = false

  # Description: Assigns IPv6 private subnet id based on the Amazon provided /56 prefix base 10 integer (0-256). Must be of equal length to the corresponding IPv4 subnet list
  # Type: list
  # private_subnet_ipv6_prefixes = []

  # Description: Indicates whether to create an IPv6-only subnet. Default: `false`
  # Type: bool
  # private_subnet_ipv6_native = false

  # Description: The type of hostnames to assign to instances in the subnet at launch. For IPv6-only subnets, an instance DNS name must be based on the instance ID. For dual-stack and IPv4-only subnets, you can specify whether DNS names use the instance IPv4 address or the instance ID. Valid values: `ip-name`, `resource-name`
  # Type: string
  # private_subnet_private_dns_hostname_type_on_launch = null

  # Description: Explicit values to use in the Name tag on private subnets. If empty, Name tags are generated
  # Type: list
  # private_subnet_names = []

  # Description: Suffix to append to private subnets name
  # Type: string
  # private_subnet_suffix = "private"

  # Description: Controls if a nat gateway route should be created to give internet access to the private subnets
  # Type: bool
  # create_private_nat_gateway_route = true

  # Description: Additional tags for the private subnets
  # Type: map
  # private_subnet_tags = {}

  # Description: Additional tags for the private subnets where the primary key is the AZ
  # Type: map
  # private_subnet_tags_per_az = {}

  # Description: Additional tags for the private route tables
  # Type: map
  # private_route_table_tags = {}

  # Description: Whether to use dedicated network ACL (not default) and custom rules for private subnets
  # Type: bool
  # private_dedicated_network_acl = false

  # Description: Private subnets inbound network ACLs
  # Type: list
  # private_inbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Private subnets outbound network ACLs
  # Type: list
  # private_outbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Additional tags for the private subnets network ACL
  # Type: map
  # private_acl_tags = {}

  # Description: A list of database subnets inside the VPC
  # Type: list
  # database_subnets = []

  # Description: Specify true to indicate that network interfaces created in the specified subnet should be assigned an IPv6 address. Default is `false`
  # Type: bool
  # database_subnet_assign_ipv6_address_on_creation = false

  # Description: Indicates whether DNS queries made to the Amazon-provided DNS Resolver in this subnet should return synthetic IPv6 addresses for IPv4-only destinations. Default: `true`
  # Type: bool
  # database_subnet_enable_dns64 = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS AAAA records. Default: `true`
  # Type: bool
  # database_subnet_enable_resource_name_dns_aaaa_record_on_launch = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS A records. Default: `false`
  # Type: bool
  # database_subnet_enable_resource_name_dns_a_record_on_launch = false

  # Description: Assigns IPv6 database subnet id based on the Amazon provided /56 prefix base 10 integer (0-256). Must be of equal length to the corresponding IPv4 subnet list
  # Type: list
  # database_subnet_ipv6_prefixes = []

  # Description: Indicates whether to create an IPv6-only subnet. Default: `false`
  # Type: bool
  # database_subnet_ipv6_native = false

  # Description: The type of hostnames to assign to instances in the subnet at launch. For IPv6-only subnets, an instance DNS name must be based on the instance ID. For dual-stack and IPv4-only subnets, you can specify whether DNS names use the instance IPv4 address or the instance ID. Valid values: `ip-name`, `resource-name`
  # Type: string
  # database_subnet_private_dns_hostname_type_on_launch = null

  # Description: Explicit values to use in the Name tag on database subnets. If empty, Name tags are generated
  # Type: list
  # database_subnet_names = []

  # Description: Suffix to append to database subnets name
  # Type: string
  # database_subnet_suffix = "db"

  # Description: Controls if separate route table for database should be created
  # Type: bool
  # create_database_subnet_route_table = false

  # Description: Controls if an internet gateway route for public database access should be created
  # Type: bool
  # create_database_internet_gateway_route = false

  # Description: Controls if a nat gateway route should be created to give internet access to the database subnets
  # Type: bool
  # create_database_nat_gateway_route = false

  # Description: Additional tags for the database route tables
  # Type: map
  # database_route_table_tags = {}

  # Description: Additional tags for the database subnets
  # Type: map
  # database_subnet_tags = {}

  # Description: Controls if database subnet group should be created (n.b. database_subnets must also be set)
  # Type: bool
  # create_database_subnet_group = true

  # Description: Name of database subnet group
  # Type: string
  # database_subnet_group_name = null

  # Description: Additional tags for the database subnet group
  # Type: map
  # database_subnet_group_tags = {}

  # Description: Whether to use dedicated network ACL (not default) and custom rules for database subnets
  # Type: bool
  # database_dedicated_network_acl = false

  # Description: Database subnets inbound network ACL rules
  # Type: list
  # database_inbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Database subnets outbound network ACL rules
  # Type: list
  # database_outbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Additional tags for the database subnets network ACL
  # Type: map
  # database_acl_tags = {}

  # Description: A list of redshift subnets inside the VPC
  # Type: list
  # redshift_subnets = []

  # Description: Specify true to indicate that network interfaces created in the specified subnet should be assigned an IPv6 address. Default is `false`
  # Type: bool
  # redshift_subnet_assign_ipv6_address_on_creation = false

  # Description: Indicates whether DNS queries made to the Amazon-provided DNS Resolver in this subnet should return synthetic IPv6 addresses for IPv4-only destinations. Default: `true`
  # Type: bool
  # redshift_subnet_enable_dns64 = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS AAAA records. Default: `true`
  # Type: bool
  # redshift_subnet_enable_resource_name_dns_aaaa_record_on_launch = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS A records. Default: `false`
  # Type: bool
  # redshift_subnet_enable_resource_name_dns_a_record_on_launch = false

  # Description: Assigns IPv6 redshift subnet id based on the Amazon provided /56 prefix base 10 integer (0-256). Must be of equal length to the corresponding IPv4 subnet list
  # Type: list
  # redshift_subnet_ipv6_prefixes = []

  # Description: Indicates whether to create an IPv6-only subnet. Default: `false`
  # Type: bool
  # redshift_subnet_ipv6_native = false

  # Description: The type of hostnames to assign to instances in the subnet at launch. For IPv6-only subnets, an instance DNS name must be based on the instance ID. For dual-stack and IPv4-only subnets, you can specify whether DNS names use the instance IPv4 address or the instance ID. Valid values: `ip-name`, `resource-name`
  # Type: string
  # redshift_subnet_private_dns_hostname_type_on_launch = null

  # Description: Explicit values to use in the Name tag on redshift subnets. If empty, Name tags are generated
  # Type: list
  # redshift_subnet_names = []

  # Description: Suffix to append to redshift subnets name
  # Type: string
  # redshift_subnet_suffix = "redshift"

  # Description: Controls if redshift should have public routing table
  # Type: bool
  # enable_public_redshift = false

  # Description: Controls if separate route table for redshift should be created
  # Type: bool
  # create_redshift_subnet_route_table = false

  # Description: Additional tags for the redshift route tables
  # Type: map
  # redshift_route_table_tags = {}

  # Description: Additional tags for the redshift subnets
  # Type: map
  # redshift_subnet_tags = {}

  # Description: Controls if redshift subnet group should be created
  # Type: bool
  # create_redshift_subnet_group = true

  # Description: Name of redshift subnet group
  # Type: string
  # redshift_subnet_group_name = null

  # Description: Additional tags for the redshift subnet group
  # Type: map
  # redshift_subnet_group_tags = {}

  # Description: Whether to use dedicated network ACL (not default) and custom rules for redshift subnets
  # Type: bool
  # redshift_dedicated_network_acl = false

  # Description: Redshift subnets inbound network ACL rules
  # Type: list
  # redshift_inbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Redshift subnets outbound network ACL rules
  # Type: list
  # redshift_outbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Additional tags for the redshift subnets network ACL
  # Type: map
  # redshift_acl_tags = {}

  # Description: A list of elasticache subnets inside the VPC
  # Type: list
  # elasticache_subnets = []

  # Description: Specify true to indicate that network interfaces created in the specified subnet should be assigned an IPv6 address. Default is `false`
  # Type: bool
  # elasticache_subnet_assign_ipv6_address_on_creation = false

  # Description: Indicates whether DNS queries made to the Amazon-provided DNS Resolver in this subnet should return synthetic IPv6 addresses for IPv4-only destinations. Default: `true`
  # Type: bool
  # elasticache_subnet_enable_dns64 = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS AAAA records. Default: `true`
  # Type: bool
  # elasticache_subnet_enable_resource_name_dns_aaaa_record_on_launch = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS A records. Default: `false`
  # Type: bool
  # elasticache_subnet_enable_resource_name_dns_a_record_on_launch = false

  # Description: Assigns IPv6 elasticache subnet id based on the Amazon provided /56 prefix base 10 integer (0-256). Must be of equal length to the corresponding IPv4 subnet list
  # Type: list
  # elasticache_subnet_ipv6_prefixes = []

  # Description: Indicates whether to create an IPv6-only subnet. Default: `false`
  # Type: bool
  # elasticache_subnet_ipv6_native = false

  # Description: The type of hostnames to assign to instances in the subnet at launch. For IPv6-only subnets, an instance DNS name must be based on the instance ID. For dual-stack and IPv4-only subnets, you can specify whether DNS names use the instance IPv4 address or the instance ID. Valid values: `ip-name`, `resource-name`
  # Type: string
  # elasticache_subnet_private_dns_hostname_type_on_launch = null

  # Description: Explicit values to use in the Name tag on elasticache subnets. If empty, Name tags are generated
  # Type: list
  # elasticache_subnet_names = []

  # Description: Suffix to append to elasticache subnets name
  # Type: string
  # elasticache_subnet_suffix = "elasticache"

  # Description: Additional tags for the elasticache subnets
  # Type: map
  # elasticache_subnet_tags = {}

  # Description: Controls if separate route table for elasticache should be created
  # Type: bool
  # create_elasticache_subnet_route_table = false

  # Description: Additional tags for the elasticache route tables
  # Type: map
  # elasticache_route_table_tags = {}

  # Description: Controls if elasticache subnet group should be created
  # Type: bool
  # create_elasticache_subnet_group = true

  # Description: Name of elasticache subnet group
  # Type: string
  # elasticache_subnet_group_name = null

  # Description: Additional tags for the elasticache subnet group
  # Type: map
  # elasticache_subnet_group_tags = {}

  # Description: Whether to use dedicated network ACL (not default) and custom rules for elasticache subnets
  # Type: bool
  # elasticache_dedicated_network_acl = false

  # Description: Elasticache subnets inbound network ACL rules
  # Type: list
  # elasticache_inbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Elasticache subnets outbound network ACL rules
  # Type: list
  # elasticache_outbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Additional tags for the elasticache subnets network ACL
  # Type: map
  # elasticache_acl_tags = {}

  # Description: A list of intra subnets inside the VPC
  # Type: list
  # intra_subnets = []

  # Description: Specify true to indicate that network interfaces created in the specified subnet should be assigned an IPv6 address. Default is `false`
  # Type: bool
  # intra_subnet_assign_ipv6_address_on_creation = false

  # Description: Indicates whether DNS queries made to the Amazon-provided DNS Resolver in this subnet should return synthetic IPv6 addresses for IPv4-only destinations. Default: `true`
  # Type: bool
  # intra_subnet_enable_dns64 = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS AAAA records. Default: `true`
  # Type: bool
  # intra_subnet_enable_resource_name_dns_aaaa_record_on_launch = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS A records. Default: `false`
  # Type: bool
  # intra_subnet_enable_resource_name_dns_a_record_on_launch = false

  # Description: Indicates whether to create a separate route table for each intra subnet. Default: `false`
  # Type: bool
  # create_multiple_intra_route_tables = false

  # Description: Assigns IPv6 intra subnet id based on the Amazon provided /56 prefix base 10 integer (0-256). Must be of equal length to the corresponding IPv4 subnet list
  # Type: list
  # intra_subnet_ipv6_prefixes = []

  # Description: Indicates whether to create an IPv6-only subnet. Default: `false`
  # Type: bool
  # intra_subnet_ipv6_native = false

  # Description: The type of hostnames to assign to instances in the subnet at launch. For IPv6-only subnets, an instance DNS name must be based on the instance ID. For dual-stack and IPv4-only subnets, you can specify whether DNS names use the instance IPv4 address or the instance ID. Valid values: `ip-name`, `resource-name`
  # Type: string
  # intra_subnet_private_dns_hostname_type_on_launch = null

  # Description: Explicit values to use in the Name tag on intra subnets. If empty, Name tags are generated
  # Type: list
  # intra_subnet_names = []

  # Description: Suffix to append to intra subnets name
  # Type: string
  # intra_subnet_suffix = "intra"

  # Description: Additional tags for the intra subnets
  # Type: map
  # intra_subnet_tags = {}

  # Description: Additional tags for the intra route tables
  # Type: map
  # intra_route_table_tags = {}

  # Description: Whether to use dedicated network ACL (not default) and custom rules for intra subnets
  # Type: bool
  # intra_dedicated_network_acl = false

  # Description: Intra subnets inbound network ACLs
  # Type: list
  # intra_inbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Intra subnets outbound network ACLs
  # Type: list
  # intra_outbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Additional tags for the intra subnets network ACL
  # Type: map
  # intra_acl_tags = {}

  # Description: A list of outpost subnets inside the VPC
  # Type: list
  # outpost_subnets = []

  # Description: Specify true to indicate that network interfaces created in the specified subnet should be assigned an IPv6 address. Default is `false`
  # Type: bool
  # outpost_subnet_assign_ipv6_address_on_creation = false

  # Description: AZ where Outpost is anchored
  # Type: string
  # outpost_az = null

  # Description: The customer owned IPv4 address pool. Typically used with the `map_customer_owned_ip_on_launch` argument. The `outpost_arn` argument must be specified when configured
  # Type: string
  # customer_owned_ipv4_pool = null

  # Description: Indicates whether DNS queries made to the Amazon-provided DNS Resolver in this subnet should return synthetic IPv6 addresses for IPv4-only destinations. Default: `true`
  # Type: bool
  # outpost_subnet_enable_dns64 = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS AAAA records. Default: `true`
  # Type: bool
  # outpost_subnet_enable_resource_name_dns_aaaa_record_on_launch = true

  # Description: Indicates whether to respond to DNS queries for instance hostnames with DNS A records. Default: `false`
  # Type: bool
  # outpost_subnet_enable_resource_name_dns_a_record_on_launch = false

  # Description: Assigns IPv6 outpost subnet id based on the Amazon provided /56 prefix base 10 integer (0-256). Must be of equal length to the corresponding IPv4 subnet list
  # Type: list
  # outpost_subnet_ipv6_prefixes = []

  # Description: Indicates whether to create an IPv6-only subnet. Default: `false`
  # Type: bool
  # outpost_subnet_ipv6_native = false

  # Description: Specify true to indicate that network interfaces created in the subnet should be assigned a customer owned IP address. The `customer_owned_ipv4_pool` and `outpost_arn` arguments must be specified when set to `true`. Default is `false`
  # Type: bool
  # map_customer_owned_ip_on_launch = false

  # Description: ARN of Outpost you want to create a subnet in
  # Type: string
  # outpost_arn = null

  # Description: The type of hostnames to assign to instances in the subnet at launch. For IPv6-only subnets, an instance DNS name must be based on the instance ID. For dual-stack and IPv4-only subnets, you can specify whether DNS names use the instance IPv4 address or the instance ID. Valid values: `ip-name`, `resource-name`
  # Type: string
  # outpost_subnet_private_dns_hostname_type_on_launch = null

  # Description: Explicit values to use in the Name tag on outpost subnets. If empty, Name tags are generated
  # Type: list
  # outpost_subnet_names = []

  # Description: Suffix to append to outpost subnets name
  # Type: string
  # outpost_subnet_suffix = "outpost"

  # Description: Additional tags for the outpost subnets
  # Type: map
  # outpost_subnet_tags = {}

  # Description: Whether to use dedicated network ACL (not default) and custom rules for outpost subnets
  # Type: bool
  # outpost_dedicated_network_acl = false

  # Description: Outpost subnets inbound network ACLs
  # Type: list
  # outpost_inbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Outpost subnets outbound network ACLs
  # Type: list
  # outpost_outbound_acl_rules = [{"cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_action":"allow","rule_number":100,"to_port":0}]

  # Description: Additional tags for the outpost subnets network ACL
  # Type: map
  # outpost_acl_tags = {}

  # Description: Controls if an Internet Gateway is created for public subnets and the related routes that connect them
  # Type: bool
  # create_igw = true

  # Description: Controls if an Egress Only Internet Gateway is created and its related routes
  # Type: bool
  # create_egress_only_igw = true

  # Description: Additional tags for the internet gateway
  # Type: map
  # igw_tags = {}

  # Description: Should be true if you want to provision NAT Gateways for each of your private networks
  # Type: bool
  # enable_nat_gateway = false

  # Description: Used to pass a custom destination route for private NAT Gateway. If not specified, the default 0.0.0.0/0 is used as a destination route
  # Type: string
  # nat_gateway_destination_cidr_block = "0.0.0.0/0"

  # Description: Should be true if you want to provision a single shared NAT Gateway across all of your private networks
  # Type: bool
  # single_nat_gateway = false

  # Description: Should be true if you want only one NAT Gateway per availability zone. Requires `var.azs` to be set, and the number of `public_subnets` created to be greater than or equal to the number of availability zones specified in `var.azs`
  # Type: bool
  # one_nat_gateway_per_az = false

  # Description: Should be true if you don't want EIPs to be created for your NAT Gateways and will instead pass them in via the 'external_nat_ip_ids' variable
  # Type: bool
  # reuse_nat_ips = false

  # Description: List of EIP IDs to be assigned to the NAT Gateways (used in combination with reuse_nat_ips)
  # Type: list
  # external_nat_ip_ids = []

  # Description: List of EIPs to be used for `nat_public_ips` output (used in combination with reuse_nat_ips and external_nat_ip_ids)
  # Type: list
  # external_nat_ips = []

  # Description: Additional tags for the NAT gateways
  # Type: map
  # nat_gateway_tags = {}

  # Description: Additional tags for the NAT EIP
  # Type: map
  # nat_eip_tags = {}

  # Description: Maps of Customer Gateway's attributes (BGP ASN and Gateway's Internet-routable external IP address)
  # Type: map
  # customer_gateways = {}

  # Description: Additional tags for the Customer Gateway
  # Type: map
  # customer_gateway_tags = {}

  # Description: Should be true if you want to create a new VPN Gateway resource and attach it to the VPC
  # Type: bool
  # enable_vpn_gateway = false

  # Description: ID of VPN Gateway to attach to the VPC
  # Type: string
  # vpn_gateway_id = ""

  # Description: The Autonomous System Number (ASN) for the Amazon side of the gateway. By default the virtual private gateway is created with the current default Amazon ASN
  # Type: string
  # amazon_side_asn = "64512"

  # Description: The Availability Zone for the VPN Gateway
  # Type: string
  # vpn_gateway_az = null

  # Description: Should be true if you want route table propagation
  # Type: bool
  # propagate_intra_route_tables_vgw = false

  # Description: Should be true if you want route table propagation
  # Type: bool
  # propagate_private_route_tables_vgw = false

  # Description: Should be true if you want route table propagation
  # Type: bool
  # propagate_public_route_tables_vgw = false

  # Description: Additional tags for the VPN gateway
  # Type: map
  # vpn_gateway_tags = {}

  # Description: Should be true to adopt and manage Default VPC
  # Type: bool
  # manage_default_vpc = false

  # Description: Name to be used on the Default VPC
  # Type: string
  # default_vpc_name = null

  # Description: Should be true to enable DNS support in the Default VPC
  # Type: bool
  # default_vpc_enable_dns_support = true

  # Description: Should be true to enable DNS hostnames in the Default VPC
  # Type: bool
  # default_vpc_enable_dns_hostnames = true

  # Description: Additional tags for the Default VPC
  # Type: map
  # default_vpc_tags = {}

  # Description: Should be true to adopt and manage default security group
  # Type: bool
  # manage_default_security_group = true

  # Description: Name to be used on the default security group
  # Type: string
  # default_security_group_name = null

  # Description: List of maps of ingress rules to set on the default security group
  # Type: list
  # default_security_group_ingress = []

  # Description: List of maps of egress rules to set on the default security group
  # Type: list
  # default_security_group_egress = []

  # Description: Additional tags for the default security group
  # Type: map
  # default_security_group_tags = {}

  # Description: Should be true to adopt and manage Default Network ACL
  # Type: bool
  # manage_default_network_acl = true

  # Description: Name to be used on the Default Network ACL
  # Type: string
  # default_network_acl_name = null

  # Description: List of maps of ingress rules to set on the Default Network ACL
  # Type: list
  # default_network_acl_ingress = [{"action":"allow","cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_no":100,"to_port":0},{"action":"allow","from_port":0,"ipv6_cidr_block":"::/0","protocol":"-1","rule_no":101,"to_port":0}]

  # Description: List of maps of egress rules to set on the Default Network ACL
  # Type: list
  # default_network_acl_egress = [{"action":"allow","cidr_block":"0.0.0.0/0","from_port":0,"protocol":"-1","rule_no":100,"to_port":0},{"action":"allow","from_port":0,"ipv6_cidr_block":"::/0","protocol":"-1","rule_no":101,"to_port":0}]

  # Description: Additional tags for the Default Network ACL
  # Type: map
  # default_network_acl_tags = {}

  # Description: Should be true to manage default route table
  # Type: bool
  # manage_default_route_table = true

  # Description: Name to be used on the default route table
  # Type: string
  # default_route_table_name = null

  # Description: List of virtual gateways for propagation
  # Type: list
  # default_route_table_propagating_vgws = []

  # Description: Configuration block of routes. See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_route_table#route
  # Type: list
  # default_route_table_routes = []

  # Description: Additional tags for the default route table
  # Type: map
  # default_route_table_tags = {}

  # Description: Whether or not to enable VPC Flow Logs
  # Type: bool
  # enable_flow_log = false

  # Description: Name to use on the VPC Flow Log IAM role created
  # Type: string
  # vpc_flow_log_iam_role_name = "vpc-flow-log-role"

  # Description: The path for the VPC Flow Log IAM Role
  # Type: string
  # vpc_flow_log_iam_role_path = null

  # Description: Determines whether the IAM role name (`vpc_flow_log_iam_role_name_name`) is used as a prefix
  # Type: bool
  # vpc_flow_log_iam_role_use_name_prefix = true

  # Description: The ARN of the Permissions Boundary for the VPC Flow Log IAM Role
  # Type: string
  # vpc_flow_log_permissions_boundary = null

  # Description: Name of the IAM policy
  # Type: string
  # vpc_flow_log_iam_policy_name = "vpc-flow-log-to-cloudwatch"

  # Description: Determines whether the name of the IAM policy (`vpc_flow_log_iam_policy_name`) is used as a prefix
  # Type: bool
  # vpc_flow_log_iam_policy_use_name_prefix = true

  # Description: The maximum interval of time during which a flow of packets is captured and aggregated into a flow log record. Valid Values: `60` seconds or `600` seconds
  # Type: number
  # flow_log_max_aggregation_interval = 600

  # Description: The type of traffic to capture. Valid values: ACCEPT, REJECT, ALL
  # Type: string
  # flow_log_traffic_type = "ALL"

  # Description: Type of flow log destination. Can be s3, kinesis-data-firehose or cloud-watch-logs
  # Type: string
  # flow_log_destination_type = "cloud-watch-logs"

  # Description: The fields to include in the flow log record, in the order in which they should appear
  # Type: string
  # flow_log_log_format = null

  # Description: The ARN of the CloudWatch log group or S3 bucket where VPC Flow Logs will be pushed. If this ARN is a S3 bucket the appropriate permissions need to be set on that bucket's policy. When create_flow_log_cloudwatch_log_group is set to false this argument must be provided
  # Type: string
  # flow_log_destination_arn = ""

  # Description: (Optional) ARN of the IAM role that allows Amazon EC2 to publish flow logs across accounts.
  # Type: string
  # flow_log_deliver_cross_account_role = null

  # Description: (Optional) The format for the flow log. Valid values: `plain-text`, `parquet`
  # Type: string
  # flow_log_file_format = null

  # Description: (Optional) Indicates whether to use Hive-compatible prefixes for flow logs stored in Amazon S3
  # Type: bool
  # flow_log_hive_compatible_partitions = false

  # Description: (Optional) Indicates whether to partition the flow log per hour. This reduces the cost and response time for queries
  # Type: bool
  # flow_log_per_hour_partition = false

  # Description: Additional tags for the VPC Flow Logs
  # Type: map
  # vpc_flow_log_tags = {}

  # Description: Whether to create CloudWatch log group for VPC Flow Logs
  # Type: bool
  # create_flow_log_cloudwatch_log_group = false

  # Description: Whether to create IAM role for VPC Flow Logs
  # Type: bool
  # create_flow_log_cloudwatch_iam_role = false

  # Description: Additional conditions of the CloudWatch role assumption policy
  # Type: list
  # flow_log_cloudwatch_iam_role_conditions = []

  # Description: The ARN for the IAM role that's used to post flow logs to a CloudWatch Logs log group. When flow_log_destination_arn is set to ARN of Cloudwatch Logs, this argument needs to be provided
  # Type: string
  # flow_log_cloudwatch_iam_role_arn = ""

  # Description: Specifies the name prefix of CloudWatch Log Group for VPC flow logs
  # Type: string
  # flow_log_cloudwatch_log_group_name_prefix = "/aws/vpc-flow-log/"

  # Description: Specifies the name suffix of CloudWatch Log Group for VPC flow logs
  # Type: string
  # flow_log_cloudwatch_log_group_name_suffix = ""

  # Description: Specifies the number of days you want to retain log events in the specified log group for VPC flow logs
  # Type: number
  # flow_log_cloudwatch_log_group_retention_in_days = null

  # Description: The ARN of the KMS Key to use when encrypting log data for VPC flow logs
  # Type: string
  # flow_log_cloudwatch_log_group_kms_key_id = null

  # Description:  Set to true if you do not wish the log group (and any logs it may contain) to be deleted at destroy time, and instead just remove the log group from the Terraform state
  # Type: bool
  # flow_log_cloudwatch_log_group_skip_destroy = false

  # Description: Specified the log class of the log group. Possible values are: STANDARD or INFREQUENT_ACCESS
  # Type: string
  # flow_log_cloudwatch_log_group_class = null

  # Description: Do you agree that Putin doesn't respect Ukrainian sovereignty and territorial integrity? More info: https://en.wikipedia.org/wiki/Putin_khuylo!
  # Type: bool
  # putin_khuylo = true

  # Description: Determines whether resources will be created
  # Type: bool
  # create = true

  # Description: Region where the resource(s) will be managed. Defaults to the region set in the provider configuration. If a value is provided, `service_endpoint` must be specified due to https://github.com/hashicorp/terraform-provider-aws/issues/42462
  # Type: string
  # region = null

  # Description: The ID of the VPC in which the endpoint will be used
  # Type: string
  # vpc_id = null

  # Description: A map of interface and/or gateway endpoints containing their properties and configurations
  # Type: any
  # endpoints = {}

  # Description: Default security group IDs to associate with the VPC endpoints
  # Type: list
  # security_group_ids = []

  # Description: Default subnets IDs to associate with the VPC endpoints
  # Type: list
  # subnet_ids = []

  # Description: A map of tags to use on all resources
  # Type: map
  # tags = {}

  # Description: Define maximum timeout for creating, updating, and deleting VPC endpoint resources
  # Type: map
  # timeouts = {}

  # Description: Determines if a security group is created
  # Type: bool
  # create_security_group = false

  # Description: Name to use on security group created. Conflicts with `security_group_name_prefix`
  # Type: string
  # security_group_name = null

  # Description: Name prefix to use on security group created. Conflicts with `security_group_name`
  # Type: string
  # security_group_name_prefix = null

  # Description: Description of the security group created
  # Type: string
  # security_group_description = null

  # Description: Security group rules to add to the security group created
  # Type: any
  # security_group_rules = {}

  # Description: A map of additional tags to add to the security group created
  # Type: map
  # security_group_tags = {}

  # Description: Determines whether resources will be created (affects all resources)
  # Type: bool
  # create = true

  # Description: Region where the resource(s) will be managed. Defaults to the Region set in the provider configuration
  # Type: string
  # region = null

  # Description: A map of tags to add to all resources
  # Type: map
  # tags = {}

  # Description: Name to use across resources created
  # Type: string
  # name = ""

  # Description: ARN of the IAM role in the destination account used for cross-account delivery of flow logs
  # Type: string
  # deliver_cross_account_role = null

  # Description: Describes the destination options for a flow log
  # Type: object
  # destination_options = null

  # Description: Elastic Network Interface ID to attach to
  # Type: string
  # eni_id = null

  # Description: Logging destination type. Valid values: `cloud-watch-logs`, `s3`, `kinesis-data-firehose`. Default: `cloud-watch-logs`
  # Type: string
  # log_destination_type = "cloud-watch-logs"

  # Description: ARN of the logging destination
  # Type: string
  # log_destination = null

  # Description: The fields to include in the flow log record
  # Type: string
  # log_format = null

  # Description: The maximum interval of time during which a flow of packets is captured and aggregated into a flow log record. Valid Values: `60` seconds (1 minute) or `600` seconds (10 minutes). Default: `600`. When `transit_gateway_id` or `transit_gateway_attachment_id` is specified, `max_aggregation_interval` must be 60 seconds (1 minute)
  # Type: number
  # max_aggregation_interval = null

  # Description: Subnet ID to attach to
  # Type: string
  # subnet_id = null

  # Description: The type of traffic to capture. Valid values: `ACCEPT`, `REJECT`, `ALL`
  # Type: string
  # traffic_type = "ALL"

  # Description: Transit Gateway Attachment ID to attach to
  # Type: string
  # transit_gateway_attachment_id = null

  # Description: Transit Gateway ID to attach to
  # Type: string
  # transit_gateway_id = null

  # Description: VPC ID to attach to
  # Type: string
  # vpc_id = null

  # Description: Map of additional tags to add to the flow log 
  # Type: map
  # flow_log_tags = {}

  # Description: Determines whether to create a CloudWatch log group for the Flow Logs
  # Type: bool
  # create_cloudwatch_log_group = true

  # Description: Name of the created CloudWatch log group
  # Type: string
  # cloudwatch_log_group_name = null

  # Description: Determines whether the log group name should be used as a prefix
  # Type: bool
  # cloudwatch_log_group_use_name_prefix = true

  # Description: Specified the log class of the log group. Possible values are: `STANDARD` or `INFREQUENT_ACCESS`
  # Type: string
  # cloudwatch_log_group_class = null

  # Description: Number of days to retain log events. Set to `0` to keep logs indefinitely
  # Type: number
  # cloudwatch_log_group_retention_in_days = 90

  # Description: If a KMS Key ARN is set, this key will be used to encrypt the corresponding log group. Please be sure that the KMS Key has an appropriate key policy (https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/encrypt-log-data-kms.html)
  # Type: string
  # cloudwatch_log_group_kms_key_id = null

  # Description: Map of additional tags to add to the CloudWatch log group
  # Type: map
  # cloudwatch_log_group_tags = {}

  # Description: Determines whether the ECS service IAM role should be created
  # Type: bool
  # create_iam_role = true

  # Description: Existing IAM role ARN
  # Type: string
  # iam_role_arn = null

  # Description: Name to use on IAM role created
  # Type: string
  # iam_role_name = null

  # Description: Determines whether the IAM role name (`iam_role_name`) is used as a prefix
  # Type: bool
  # iam_role_use_name_prefix = true

  # Description: IAM role path
  # Type: string
  # iam_role_path = null

  # Description: Description of the role
  # Type: string
  # iam_role_description = null

  # Description: ARN of the policy that is used to set the permissions boundary for the IAM role
  # Type: string
  # iam_role_permissions_boundary = null

  # Description: A map of additional tags to add to the IAM role created
  # Type: map
  # iam_role_tags = {}

  # Description: A map of IAM policy [statements](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#statement) for custom trust policy permissions
  # Type: map
  # iam_role_trust_policy_permissions = null

  # Description: A map of IAM policy [statements](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#statement) for inline policy permissions
  # Type: map
  # iam_role_permissions = null

  # Description: ARN of the existing Kinesis Data Firehose delivery stream. Required when `log_destination_type` is `kinesis-data-firehose`
  # Type: string
  # kinesis_data_firehose_arn = null

  # Description: Map of default values which will be used for each item.
  # Type: any
  # defaults = {}

  # Description: Maps of items to create a wrapper from. Values are passed through to the module.
  # Type: any
  # items = {}

  # Description: Map of default values which will be used for each item.
  # Type: any
  # defaults = {}

  # Description: Maps of items to create a wrapper from. Values are passed through to the module.
  # Type: any
  # items = {}

  # Description: Map of default values which will be used for each item.
  # Type: any
  # defaults = {}

  # Description: Maps of items to create a wrapper from. Values are passed through to the module.
  # Type: any
  # items = {}

}
